import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/lib/personal-supabase/auth-middleware";

async function assertAdmin(db:any,userId:string){const {data,error}=await db.from("user_roles").select("role").eq("user_id",userId).in("role",["admin","super_admin"]).limit(1);if(error)throw new Error(error.message);if(!data?.length)throw new Error("Unauthorized");}
async function adminDb(context:any){await assertAdmin(context.supabase,context.userId);const {supabaseAdmin}=await import("@/integrations/supabase/client.server");return supabaseAdmin as any;}

export const listCustomerFeedback=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=await adminDb(context);const [{data:reviews,error:re},{data:questions,error:qe},{data:comments,error:ce},{data:products,error:pe},{data:posts,error:poste}]=await Promise.all([db.from("product_reviews").select("id,product_id,user_id,author_name,rating,body,image_urls,verified_purchase,status,admin_reply,replied_at,created_at").order("created_at",{ascending:false}).limit(1000),db.from("product_questions").select("id,product_id,user_id,author_name,question,answer,answered_at,status,created_at").order("created_at",{ascending:false}).limit(1000),db.from("social_post_comments").select("id,post_id,user_id,author_name,body,status,admin_reply,replied_at,created_at").order("created_at",{ascending:false}).limit(1000),db.from("products").select("id,name,slug").limit(2000),db.from("social_posts").select("id,author_name,body").limit(2000)]);for(const e of [re,qe,ce,pe,poste])if(e)throw new Error(e.message);return{reviews:reviews??[],questions:questions??[],comments:comments??[],products:products??[],posts:posts??[]};});

const Reply=z.object({id:z.string().uuid(),reply:z.string().max(5000).nullable()});
export const replyCustomerReview=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(i=>Reply.parse(i)).handler(async({data,context})=>{const db=await adminDb(context);const patch={admin_reply:data.reply?.trim()||null,replied_at:data.reply?.trim()?new Date().toISOString():null};const {error}=await db.from("product_reviews").update(patch).eq("id",data.id);if(error)throw new Error(error.message);return true;});
export const answerCustomerQuestion=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(i=>Reply.parse(i)).handler(async({data,context})=>{const db=await adminDb(context);const answer=data.reply?.trim()||null;const {error}=await db.from("product_questions").update({answer,answered_at:answer?new Date().toISOString():null}).eq("id",data.id);if(error)throw new Error(error.message);return true;});
export const replyPostComment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(i=>Reply.parse(i)).handler(async({data,context})=>{const db=await adminDb(context);const patch={admin_reply:data.reply?.trim()||null,replied_at:data.reply?.trim()?new Date().toISOString():null};const {error}=await db.from("social_post_comments").update(patch).eq("id",data.id);if(error)throw new Error(error.message);return true;});
const Delete=z.object({id:z.string().uuid()});
export const deleteCustomerReview=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(i=>Delete.parse(i)).handler(async({data,context})=>{const db=await adminDb(context);const {error}=await db.from("product_reviews").delete().eq("id",data.id);if(error)throw new Error(error.message);return true;});
export const deleteCustomerQuestion=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(i=>Delete.parse(i)).handler(async({data,context})=>{const db=await adminDb(context);const {error}=await db.from("product_questions").delete().eq("id",data.id);if(error)throw new Error(error.message);return true;});
export const deletePostComment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(i=>Delete.parse(i)).handler(async({data,context})=>{const db=await adminDb(context);const {error}=await db.from("social_post_comments").delete().eq("id",data.id);if(error)throw new Error(error.message);return true;});
