import { QueryClient, QueryClientProvider, useQueryClient } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect } from "react";
import { Toaster } from "@/components/ui/sonner";
import { supabase } from "@/lib/personal-supabase/client";
import { SiteVisitorTracker } from "@/components/SiteVisitorTracker";
import { FacebookPixel } from "@/components/layout/FacebookPixel";
import appCss from "../styles.css?url";
import landingCheckoutCss from "../landing-checkout.css?url";
function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold text-brand">৪০৪</h1><h2 className="mt-4 text-xl font-semibold">পেজটি খুঁজে পাওয়া যায়নি</h2><Link to="/" className="mt-6 inline-flex rounded-md bg-brand px-4 py-2 text-sm text-white hover:bg-brand-dark">হোমে ফিরে যান</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold">পেজ লোড হয়নি</h1><p className="mt-2 text-sm text-muted-foreground">{error.message}</p><button onClick={()=>{router.invalidate();reset()}} className="mt-6 rounded-md bg-brand px-4 py-2 text-sm text-white hover:bg-brand-dark">আবার চেষ্টা করুন</button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"Sheikh Seeds — অরিজিনাল বীজ, গার্ডেন টুলস ও সার"},{name:"description",content:"Sheikh Seeds — অরিজিনাল সবজি, ফল ও ফুলের বীজ, গার্ডেন টুলস, সার ও কীটনাশক অনলাইনে অর্ডার করুন। সারাদেশে হোম ডেলিভারি ও ক্যাশ অন ডেলিভারি।"},{property:"og:site_name",content:"Sheikh Seeds"},{property:"og:title",content:"Sheikh Seeds — অরিজিনাল বীজ, গার্ডেন টুলস ও সার"},{property:"og:description",content:"Sheikh Seeds — অরিজিনাল বীজ, গার্ডেন টুলস ও সার"},{property:"og:type",content:"website"},{property:"og:locale",content:"bn_BD"},{name:"robots",content:"index, follow, max-image-preview:large"},{name:"author",content:"Sheikh Seeds"},{name:"theme-color",content:"#0d4a29"}],links:[{rel:"stylesheet",href:appCss},{rel:"stylesheet",href:landingCheckoutCss},{rel:"icon",type:"image/svg+xml",href:"/sheikh-seeds-logo.svg"},{rel:"apple-touch-icon",href:"/sheikh-seeds-logo.svg"},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://yqhtenonavuzxzemaiyk.supabase.co",crossOrigin:"anonymous"},{rel:"preconnect",href:"https://bvuhvzccziuniujeogng.supabase.co",crossOrigin:"anonymous"},{rel:"dns-prefetch",href:"https://connect.facebook.net"}],scripts:[{type:"text/javascript",children:"(()=>{const p=location.pathname;const href=p.startsWith('/admin')?'/admin.webmanifest':'/site.webmanifest';let l=document.querySelector('link[rel=manifest]');if(!l){l=document.createElement('link');l.rel='manifest';document.head.appendChild(l)}l.href=href})()"},{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"OnlineStore","@id":"https://oronnonogor.com/#organization",name:"Sheikh Seeds",alternateName:["Sheikh Seeds","Sheikh Seeds BD"],slogan:"দেশী ও বিদেশী বীজ এর একটি বিশ্বস্ত প্রতিষ্ঠান",description:"Sheikh Seeds একটি অনলাইন গার্ডেন শপ — অরিজিনাল সবজি, ফল ও ফুলের বীজ, গার্ডেন টুলস, সার ও কীটনাশক সারাদেশে ডেলিভারি করে।",url:"https://oronnonogor.com",logo:"https://oronnonogor.com/sheikh-seeds-logo.svg",image:"https://oronnonogor.com/og-oronno-nogor.jpg",areaServed:{"@type":"Country",name:"Bangladesh"},address:{"@type":"PostalAddress",addressCountry:"BD"},paymentAccepted:"Cash on Delivery, bKash",currenciesAccepted:"BDT"})},{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"WebSite","@id":"https://oronnonogor.com/#website",name:"Sheikh Seeds",alternateName:"Sheikh Seeds",inLanguage:"bn-BD",url:"https://oronnonogor.com",publisher:{"@id":"https://oronnonogor.com/#organization"},potentialAction:{"@type":"SearchAction",target:{"@type":"EntryPoint",urlTemplate:"https://oronnonogor.com/shop?q={search_term_string}"},"query-input":"required name=search_term_string"}})}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:React.ReactNode}){return <html lang="bn"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><AuthCacheSync/><FacebookPixel/><SiteVisitorTracker/><Outlet/><Toaster richColors position="top-center"/></QueryClientProvider>}
function AuthCacheSync(){const router=useRouter();const queryClient=useQueryClient();useEffect(()=>{const {data:{subscription}}=supabase.auth.onAuthStateChange(event=>{if(event==="INITIAL_SESSION"||event==="TOKEN_REFRESHED"||event==="SIGNED_IN"||event==="USER_UPDATED")return;if(event==="SIGNED_OUT"){router.invalidate();queryClient.invalidateQueries()}});return()=>subscription.unsubscribe()},[queryClient,router]);return null}
