import { createFileRoute, useNavigate, Link } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { SiteLayout } from "@/components/layout/SiteLayout";
import { supabase } from "@/lib/personal-supabase/client";
import { useAuth } from "@/lib/auth";
import { customerSendOtp, customerVerifyOtp } from "@/lib/customer-auth.functions";
import { Phone, ShieldCheck, ArrowRight, Loader2, RotateCcw, Gift, Truck, UsersRound, Sparkles } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/customer-login")({ component: CustomerLogin, head: () => ({ meta: [{ title: "অ্যাকাউন্ট তৈরি — Sheikh Seeds" }, { name: "description", content: "Sheikh Seeds কাস্টমার অ্যাকাউন্ট তৈরি করুন এবং অর্ডার ট্র্যাকিং ও বিশেষ সুবিধা পান।" }, { name: "robots", content: "noindex" }] }) });

function CustomerLogin(){
  const navigate=useNavigate(); const {user,initialized}=useAuth(); const sendOtp=useServerFn(customerSendOtp); const verifyOtp=useServerFn(customerVerifyOtp);
  const [step,setStep]=useState<"phone"|"code">("phone"); const [phone,setPhone]=useState(""); const [code,setCode]=useState(""); const [digits,setDigits]=useState(["","","",""]); const [busy,setBusy]=useState(false); const refs=useRef<Array<HTMLInputElement|null>>([]); const valid=/^01[3-9][0-9]{8}$/.test(phone.replace(/\D/g,""));
  useEffect(()=>{if(initialized&&user)navigate({to:"/profile",replace:true})},[initialized,user,navigate]);
  const doSend=async()=>{const p=phone.replace(/\D/g,"");if(!/^01[3-9][0-9]{8}$/.test(p))return toast.error("সঠিক ১১ ডিজিটের মোবাইল নম্বর দিন (০১XXXXXXXXX)");setBusy(true);try{await sendOtp({data:{phone:p}});setPhone(p);setDigits(["","","",""]);setCode("");setStep("code");toast.success("আপনার নম্বরে OTP পাঠানো হয়েছে");setTimeout(()=>refs.current[0]?.focus(),120)}catch(e){toast.error(e instanceof Error?e.message:"OTP পাঠানো যায়নি")}finally{setBusy(false)}};
  const update=(i:number,v:string)=>{const d=v.replace(/\D/g,"").slice(-1);const n=[...digits];n[i]=d;setDigits(n);setCode(n.join(""));if(d&&i<3)refs.current[i+1]?.focus()};
  const key=(i:number,e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==="Backspace"&&!digits[i]&&i>0){const n=[...digits];n[i-1]="";setDigits(n);setCode(n.join(""));refs.current[i-1]?.focus()}};
  const paste=(e:React.ClipboardEvent<HTMLInputElement>)=>{e.preventDefault();const p=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,4);if(!p)return;const n=["","","",""];p.split("").forEach((x,i)=>n[i]=x);setDigits(n);setCode(p);refs.current[Math.min(p.length,4)-1]?.focus()};
  const doVerify=async()=>{const otp=code.replace(/\D/g,"");if(otp.length!==4)return toast.error("৪ ডিজিটের OTP কোডটি সম্পূর্ণ লিখুন");setBusy(true);try{const res=await verifyOtp({data:{phone,code:otp}});const {error}=await supabase.auth.verifyOtp({type:"email",token_hash:res.tokenHash});if(error)throw new Error(error.message);toast.success("আপনার অ্যাকাউন্ট তৈরি হয়েছে");navigate({to:"/profile"})}catch(e){toast.error(e instanceof Error?e.message:"OTP কোডটি সঠিক নয়")}finally{setBusy(false)}};
  if(initialized&&user)return null;
  return <SiteLayout><div className="min-h-[calc(100vh-160px)] bg-gradient-to-b from-brand/[0.04] to-background py-5 sm:py-9"><div className="container mx-auto px-3"><div className="mx-auto w-full max-w-md overflow-hidden rounded-[28px] border bg-white shadow-[0_20px_70px_rgba(20,83,45,.12)]">
    <div className="relative overflow-hidden bg-gradient-to-br from-brand via-brand-dark to-emerald-950 px-5 py-7 text-white sm:px-7"><div className="absolute -right-10 -top-14 h-40 w-40 rounded-full bg-lime-300/20 blur-3xl"/><div className="relative flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-white/15 bg-white/10"><UserPlus className="h-6 w-6"/></div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/70">Sheikh Seeds</p><h1 className="text-xl font-black">কাস্টমার অ্যাকাউন্ট তৈরি</h1><p className="mt-0.5 text-xs text-white/80">একবার তৈরি করুন, সব সুবিধা একসাথে পান</p></div></div></div>
    <div className="p-4 sm:p-6">{step==="phone"?<><div className="mb-5 grid grid-cols-3 gap-2"><Benefit icon={<Truck/>} text="অর্ডার ট্র্যাকিং"/><Benefit icon={<Gift/>} text="বোনাস ও গিফট"/><Benefit icon={<UsersRound/>} text="কৃষি কমিউনিটি"/></div><div className="space-y-4"><div><label className="text-sm font-bold">মোবাইল নম্বর</label><p className="mt-1 text-xs text-muted-foreground">আপনার ১১ ডিজিটের বাংলাদেশি নম্বরটি দিন</p><div className="mt-2 flex items-center gap-2 rounded-2xl border bg-muted/20 px-3.5 focus-within:border-brand focus-within:ring-4 focus-within:ring-brand/10"><Phone className="h-4 w-4 text-brand-dark"/><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,11))} onKeyDown={e=>e.key==="Enter"&&valid&&doSend()} inputMode="numeric" autoComplete="tel" placeholder="01XXXXXXXXX" className="min-w-0 flex-1 bg-transparent py-3.5 text-[15px] font-semibold outline-none"/></div></div><button onClick={doSend} disabled={busy||!valid} className="w-full rounded-2xl bg-brand py-3.5 font-bold text-white shadow-lg shadow-brand/20 disabled:opacity-50">{busy?<Loader2 className="mx-auto h-5 w-5 animate-spin"/>:<><span>অ্যাকাউন্ট তৈরি শুরু করুন</span><ArrowRight className="ml-2 inline h-4 w-4"/></>}</button></div></>:<div className="space-y-5"><div className="text-center"><div className="mx-auto mb-2 flex h-11 w-11 items-center justify-center rounded-full bg-brand/10 text-brand-dark"><ShieldCheck className="h-5 w-5"/></div><h2 className="text-base font-extrabold">OTP দিয়ে অ্যাকাউন্ট যাচাই করুন</h2><p className="mt-1 text-xs text-muted-foreground"><b className="text-foreground">{phone}</b> নম্বরে ৪ ডিজিটের কোড পাঠানো হয়েছে</p></div><div className="flex justify-center gap-2.5">{digits.map((d,i)=><input key={i} ref={e=>{refs.current[i]=e}} value={d} onChange={e=>update(i,e.target.value)} onKeyDown={e=>key(i,e)} onPaste={paste} inputMode="numeric" maxLength={1} className="h-14 w-14 rounded-2xl border-2 bg-muted/20 text-center text-2xl font-black outline-none focus:border-brand focus:ring-4 focus:ring-brand/10 sm:h-16 sm:w-16"/>)}</div><button onClick={doVerify} disabled={busy||code.length!==4} className="w-full rounded-2xl bg-brand py-3.5 font-bold text-white shadow-lg shadow-brand/20 disabled:opacity-50">{busy?<Loader2 className="mx-auto h-5 w-5 animate-spin"/>:<><ShieldCheck className="mr-2 inline h-4 w-4"/>অ্যাকাউন্ট তৈরি সম্পন্ন করুন</>}</button><button onClick={()=>{setStep("phone");setDigits(["","","",""]);setCode("")}} className="mx-auto flex items-center gap-1.5 text-xs font-semibold text-muted-foreground"><RotateCcw className="h-3.5 w-3.5"/> নম্বর পরিবর্তন করুন</button></div>}<div className="mt-5 border-t pt-4 text-center text-[11px] leading-5 text-muted-foreground">নিরাপদ OTP ভেরিফিকেশনের মাধ্যমে অ্যাকাউন্ট তৈরি হবে। তৈরি হলে আপনার প্রোফাইল থেকে অর্ডার ও ব্যক্তিগত তথ্য পরিচালনা করতে পারবেন।<br/><Link to="/shop" className="font-bold text-brand-dark">অ্যাকাউন্ট ছাড়াও কেনাকাটা করা যাবে</Link></div></div>
  </div></div></div></SiteLayout>;
}
function Benefit({icon,text}:{icon:React.ReactNode;text:string}){return <div className="rounded-xl bg-brand/[0.05] p-2 text-center"><div className="mx-auto flex h-8 w-8 items-center justify-center rounded-lg bg-brand/10 text-brand-dark [&_svg]:h-4 [&_svg]:w-4">{icon}</div><p className="mt-1 text-[10px] font-bold leading-4">{text}</p></div>}
