import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { SiteLayout } from "@/components/layout/SiteLayout";
import { useCustomer, db } from "@/lib/customer-account";
import { Heart, MessageCircle, Send, Plus, Share2, Trash2, X, Image as ImageIcon, Loader2 } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/social")({ component: SocialPage, head:()=>({meta:[{title:"কমিউনিটি — Sheikh Seeds"},{name:"description",content:"বাগানিদের সোশ্যাল কমিউনিটি — পোস্ট, রিয়েক্ট, কমেন্ট, স্টোরি ও শেয়ার করুন।"}]}) });

type Post={id:string;user_id:string|null;author_name:string;author_avatar?:string|null;body:string;image_urls?:string[];like_count:number;comment_count:number;created_at:string};
type Reaction={post_id:string;user_id:string;reaction:string};
type Comment={id:string;post_id:string;user_id:string|null;author_name:string;body:string;parent_id:string|null;created_at:string};
type Story={id:string;user_id:string|null;author_name:string;author_avatar?:string|null;body:string|null;image_url:string|null;created_at:string;expires_at:string};
const RS=[['like','👍','লাইক'],['love','❤️','লাভ'],['haha','😂','হাহা'],['wow','😮','ওয়াও'],['sad','😢','স্যাড'],['angry','😡','রাগ']] as const;
const ago=(s:string)=>{const d=Math.max(0,(Date.now()-new Date(s).getTime())/1000);return d<60?'এইমাত্র':d<3600?`${Math.floor(d/60)} মিনিট আগে`:d<86400?`${Math.floor(d/3600)} ঘণ্টা আগে`:new Date(s).toLocaleDateString('bn-BD',{day:'numeric',month:'short'})};
function Avatar({name,src,sm=false}:{name:string;src?:string|null;sm?:boolean}){return src?<img src={src} alt="" className={`${sm?'w-8 h-8':'w-10 h-10'} rounded-full object-cover shrink-0`}/>:<div className={`${sm?'w-8 h-8 text-xs':'w-10 h-10'} rounded-full bg-emerald-100 text-emerald-700 font-bold flex items-center justify-center shrink-0`}>{name?.slice(0,1)||'🌱'}</div>}

function SocialPage(){
 const {user,isLoggedIn,displayName,profile}=useCustomer(); const qc=useQueryClient();
 const [text,setText]=useState(''); const [media,setMedia]=useState(''); const [storyOpen,setStoryOpen]=useState(false); const [storyText,setStoryText]=useState(''); const [storyImg,setStoryImg]=useState(''); const [busy,setBusy]=useState(false);
 const posts=useQuery({queryKey:['social-posts'],staleTime:15000,queryFn:async()=>{const {data,error}=await db.from('social_posts').select('id,user_id,author_name,author_avatar,body,image_urls,like_count,comment_count,created_at').eq('status','approved').order('created_at',{ascending:false}).limit(50);if(error)throw error;return (data??[]) as Post[]}});
 const stories=useQuery({queryKey:['social-stories'],staleTime:15000,queryFn:async()=>{const {data}=await db.from('social_stories').select('id,user_id,author_name,author_avatar,body,image_url,created_at,expires_at').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(30);return (data??[]) as Story[]}});
 const reactions=useQuery({queryKey:['social-reactions',posts.data?.map(p=>p.id).join(',')],enabled:!!posts.data?.length,queryFn:async()=>{const {data}=await db.from('social_post_reactions').select('post_id,user_id,reaction').in('post_id',(posts.data??[]).map(p=>p.id));return (data??[]) as Reaction[]}});
 const createPost=async()=>{if(!user)return toast.error('পোস্ট করতে লগইন করুন');if(!text.trim()&&!media.trim())return toast.error('কিছু লিখুন');setBusy(true);const {error}=await db.from('social_posts').insert({user_id:user.id,author_name:displayName,author_avatar:profile?.avatar_url||null,body:text.trim(),image_urls:media.trim()?[media.trim()]:[]});setBusy(false);if(error)return toast.error(error.message);setText('');setMedia('');toast.success('পোস্ট প্রকাশিত হয়েছে');qc.invalidateQueries({queryKey:['social-posts']})};
 const addStory=async()=>{if(!user||(!storyText.trim()&&!storyImg.trim()))return;const {error}=await db.from('social_stories').insert({user_id:user.id,author_name:displayName,author_avatar:profile?.avatar_url||null,body:storyText.trim()||null,image_url:storyImg.trim()||null});if(error)return toast.error(error.message);setStoryText('');setStoryImg('');setStoryOpen(false);toast.success('Story যোগ হয়েছে');qc.invalidateQueries({queryKey:['social-stories']})};
 const react=async(p:Post,r:string)=>{if(!user)return toast.error('রিয়েক্ট করতে লগইন করুন');const cur=reactions.data?.find(x=>x.post_id===p.id&&x.user_id===user.id)?.reaction;if(cur===r)await db.from('social_post_reactions').delete().eq('post_id',p.id).eq('user_id',user.id);else await db.from('social_post_reactions').upsert({post_id:p.id,user_id:user.id,reaction:r},{onConflict:'post_id,user_id'});qc.invalidateQueries({queryKey:['social-reactions']})};
 return <SiteLayout><div className="min-h-screen bg-[#f0f2f5] pb-10"><div className="max-w-2xl mx-auto">
  <div className="bg-white border-b sm:border sm:rounded-b-2xl p-3"><div className="flex items-center justify-between"><div><h1 className="text-xl font-extrabold">কমিউনিটি</h1><p className="text-xs text-slate-500">বাগানিদের গল্প ও অভিজ্ঞতা 🌱</p></div><button onClick={()=>setStoryOpen(true)} className="rounded-full bg-emerald-50 text-emerald-700 px-3 py-2 text-sm font-bold flex gap-1"><Plus className="w-4 h-4"/>Story</button></div></div>
  <div className="bg-white border-b sm:border sm:rounded-2xl sm:mt-3 p-3"><div className="flex gap-2.5"><Avatar name={displayName} src={profile?.avatar_url}/>{isLoggedIn?<button onClick={()=>document.getElementById('composer')?.focus()} className="flex-1 text-left bg-[#f0f2f5] rounded-full px-4 text-sm text-slate-500">{displayName}, আজ কী শেয়ার করবেন?</button>:<Link to="/customer-login" className="flex-1 bg-[#f0f2f5] rounded-full px-4 py-2.5 text-sm text-slate-500">পোস্ট করতে লগইন করুন</Link>}</div>{isLoggedIn&&<div className="mt-3 border-t pt-2 flex"><button onClick={()=>document.getElementById('composer')?.focus()} className="flex-1 py-2 text-sm font-semibold text-slate-600"><ImageIcon className="inline w-5 h-5 mr-1 text-emerald-600"/>Photo / Video</button><button onClick={()=>setStoryOpen(true)} className="flex-1 py-2 text-sm font-semibold text-slate-600">Story</button></div>}</div>
  {storyOpen&&<div className="bg-white border-b sm:border sm:rounded-2xl sm:mt-2 p-3"><div className="flex justify-between mb-2"><b>নতুন Story</b><button onClick={()=>setStoryOpen(false)}><X className="w-5 h-5"/></button></div><textarea value={storyText} onChange={e=>setStoryText(e.target.value)} rows={2} placeholder="Story লিখুন..." className="w-full rounded-xl bg-slate-50 p-3 text-sm outline-none"/><input value={storyImg} onChange={e=>setStoryImg(e.target.value)} placeholder="ছবির URL (ঐচ্ছিক)" className="w-full mt-2 rounded-xl bg-slate-50 p-3 text-sm outline-none"/><button onClick={addStory} className="w-full mt-2 rounded-xl bg-emerald-600 text-white py-2.5 font-bold">Story শেয়ার করুন</button></div>}
  {(stories.data??[]).length>0&&<div className="bg-white border-b sm:border sm:rounded-2xl sm:mt-2 p-3 overflow-x-auto"><div className="flex gap-3">{stories.data!.map(s=><button key={s.id} onClick={()=>alert(s.body||'Story')} className="w-16 shrink-0 text-center"><div className="p-[2px] rounded-full bg-gradient-to-tr from-amber-400 via-fuchsia-500 to-emerald-500"><div className="bg-white rounded-full p-[2px]"><Avatar name={s.author_name} src={s.author_avatar}/></div></div><span className="block truncate text-xs font-semibold mt-1">{s.author_name}</span></button>)}</div></div>}
  {isLoggedIn&&<div className="bg-white border-b sm:border sm:rounded-2xl sm:mt-2 p-3"><textarea id="composer" value={text} onChange={e=>setText(e.target.value)} rows={2} placeholder="আপনার বাগানের গল্প লিখুন..." className="w-full resize-none outline-none text-[15px]"/><input value={media} onChange={e=>setMedia(e.target.value)} placeholder="ছবি/ভিডিও URL (ঐচ্ছিক)" className="w-full bg-slate-50 rounded-xl px-3 py-2 text-xs outline-none"/><button onClick={createPost} disabled={busy} className="float-right mt-2 bg-emerald-600 text-white rounded-lg px-5 py-2 text-sm font-bold flex gap-2">{busy?<Loader2 className="w-4 h-4 animate-spin"/>:<Send className="w-4 h-4"/>}পোস্ট</button><div className="clear-both"/></div>}
  <div className="mt-2 sm:mt-3 space-y-2 sm:space-y-3">{posts.isLoading?<div className="bg-white p-10 text-center text-slate-500">লোড হচ্ছে...</div>:posts.data?.length?posts.data.map(p=><PostCard key={p.id} post={p} userId={user?.id} displayName={displayName} reactions={reactions.data??[]} onReact={r=>react(p,r)} onDelete={async()=>{if(p.user_id!==user?.id)return;await db.from('social_posts').delete().eq('id',p.id);qc.invalidateQueries({queryKey:['social-posts']})}}/>):<div className="bg-white p-10 text-center text-slate-500">এখনো কোনো পোস্ট নেই 🌱</div>}</div>
 </div></div></SiteLayout>;
}

function PostCard({post,userId,displayName,reactions,onReact,onDelete}:{post:Post;userId?:string;displayName:string;reactions:Reaction[];onReact:(r:string)=>void;onDelete:()=>void}){
 const [open,setOpen]=useState(false);const [picker,setPicker]=useState(false);const [comment,setComment]=useState('');const [reply,setReply]=useState<string|null>(null);const qc=useQueryClient();
 const cq=useQuery({queryKey:['social-comments',post.id],enabled:open,queryFn:async()=>{const {data}=await db.from('social_post_comments').select('id,post_id,user_id,author_name,body,parent_id,created_at').eq('post_id',post.id).eq('status','approved').order('created_at',{ascending:true});return (data??[]) as Comment[]}});
 const mine=reactions.find(r=>r.post_id===post.id&&r.user_id===userId)?.reaction;const count=reactions.filter(r=>r.post_id===post.id).length;const roots=useMemo(()=>cq.data?.filter(c=>!c.parent_id)??[],[cq.data]);const children=(id:string)=>cq.data?.filter(c=>c.parent_id===id)??[];
 const add=async()=>{if(!userId||!comment.trim())return toast.error('কমেন্ট করতে লগইন করুন');const {error}=await db.from('social_post_comments').insert({post_id:post.id,user_id:userId,author_name:displayName,body:comment.trim(),parent_id:reply});if(error)return toast.error(error.message);setComment('');setReply(null);qc.invalidateQueries({queryKey:['social-comments',post.id]});qc.invalidateQueries({queryKey:['social-posts']})};
 const share=async()=>{const u=`${location.origin}/social#${post.id}`;try{await navigator.clipboard.writeText(u);toast.success('লিংক কপি হয়েছে')}catch{toast.info('পোস্টের লিংক কপি করা যায়নি')}};
 return <article className="bg-white border-b sm:border sm:rounded-2xl overflow-visible"><div className="p-3"><div className="flex items-center gap-2.5"><Avatar name={post.author_name} src={post.author_avatar}/><div className="flex-1"><b className="text-sm">{post.author_name}</b><div className="text-[11px] text-slate-500">{ago(post.created_at)} · 🌱</div></div>{post.user_id===userId&&<button onClick={onDelete} className="text-slate-400 hover:text-red-500"><Trash2 className="w-4 h-4"/></button>}</div><p className="mt-2.5 whitespace-pre-wrap text-[15px] leading-6">{post.body}</p></div>{post.image_urls?.[0]&&<img src={post.image_urls[0]} alt="" loading="lazy" className="w-full max-h-[560px] object-cover bg-slate-100"/>}
 <div className="px-3 py-2 flex justify-between text-xs text-slate-500"><span>{count>0?`${[...new Set(reactions.filter(r=>r.post_id===post.id).map(r=>RS.find(x=>x[0]===r.reaction)?.[1]||'👍'))].slice(0,3).join(' ')} ${count}`:''}</span><span>{post.comment_count?`${post.comment_count} কমেন্ট`:''}</span></div>
 <div className="mx-3 border-t flex"><div className="flex-1 relative"><button onClick={()=>onReact(mine||'like')} onContextMenu={e=>{e.preventDefault();setPicker(v=>!v)}} className={`w-full py-2.5 font-semibold text-sm ${mine?'text-emerald-600':'text-slate-600'}`}>{RS.find(x=>x[0]===mine)?.[1]||'👍'} {RS.find(x=>x[0]===mine)?.[2]||'রিয়েক্ট'}</button>{picker&&<div className="absolute bottom-11 left-0 bg-white shadow-xl border rounded-full p-1 flex gap-1 z-20">{RS.map(x=><button key={x[0]} title={x[2]} onClick={()=>{onReact(x[0]);setPicker(false)}} className="text-xl p-1 hover:scale-125 transition">{x[1]}</button>)}</div>}</div><button onClick={()=>setOpen(v=>!v)} className="flex-1 py-2.5 font-semibold text-sm text-slate-600"><MessageCircle className="inline w-4 h-4 mr-1"/>কমেন্ট</button><button onClick={share} className="flex-1 py-2.5 font-semibold text-sm text-slate-600"><Share2 className="inline w-4 h-4 mr-1"/>শেয়ার</button></div>
 {open&&<div className="border-t bg-slate-50 p-3 space-y-2">{roots.map(c=><div key={c.id}><div className="flex gap-2"><Avatar name={c.author_name} sm/><div className="bg-white rounded-2xl px-3 py-2"><b className="text-xs">{c.author_name}</b><p className="text-sm">{c.body}</p></div></div><button onClick={()=>setReply(c.id)} className="ml-10 text-[11px] font-bold text-slate-500">Reply</button>{children(c.id).map(r=><div key={r.id} className="ml-10 mt-1 flex gap-2"><Avatar name={r.author_name} sm/><div className="bg-white rounded-2xl px-3 py-2"><b className="text-xs">{r.author_name}</b><p className="text-sm">{r.body}</p></div></div>)}</div>)}<div className="flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder={reply?'রিপ্লাই লিখুন...':'কমেন্ট লিখুন...'} className="flex-1 rounded-full border bg-white px-4 py-2 text-sm outline-none"/><button onClick={add} className="rounded-full bg-emerald-600 text-white p-2.5"><Send className="w-4 h-4"/></button></div>{reply&&<button onClick={()=>setReply(null)} className="text-[11px] text-red-500">রিপ্লাই বাতিল</button>}</div>}
 </article>;
}
