import { useRef,useState } from 'react';
import { Search,Users,Play,Compass,Trophy,Image as ImageIcon,Plus,Type,Send,X,Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/lib/personal-supabase/client';
import { useCustomer } from '@/lib/customer-account';
import { safeUUID } from "@/lib/uuid";

const tabs=[['feed','নিউজ ফিড',Users],['videos','ভিডিও',Play],['explore','এক্সপ্লোর',Compass],['top','সেরা',Trophy]] as const;
const read=(f:File)=>new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=no;r.readAsDataURL(f)});
const isVideo=(f?:File|string|null)=>!!f&&((typeof f==='string'&&(/^(data:video\/)|\.(mp4|webm|mov|m4v)(\?|$)/i.test(f)))||(typeof f!=='string'&&f.type.startsWith('video/')));
export function PremiumCommunity(){
 const {user,isLoggedIn,displayName,profile}=useCustomer();
 const storyInput=useRef<HTMLInputElement>(null),postInput=useRef<HTMLInputElement>(null);
 const [tab,setTab]=useState('feed'),[q,setQ]=useState('');
 const [storyOpen,setStoryOpen]=useState(false),[storyFile,setStoryFile]=useState<File|null>(null),[storyPreview,setStoryPreview]=useState(''),[storyText,setStoryText]=useState(''),[storyPos,setStoryPos]=useState(50),[posting,setPosting]=useState(false);
 const [postOpen,setPostOpen]=useState(false),[postText,setPostText]=useState(''),[postFiles,setPostFiles]=useState<File[]>([]),[postPreview,setPostPreview]=useState<string[]>([]);
 const openStory=()=>{if(!isLoggedIn)return toast.error('Story দিতে লগইন করুন');storyInput.current?.click()};
 const chooseStory=async(fs:FileList|null)=>{const f=fs?.[0];if(!f)return;if(!/^(image|video)\//.test(f.type))return toast.error('শুধু ছবি বা ভিডিও নির্বাচন করুন');if(f.size>25*1024*1024)return toast.error('সর্বোচ্চ ২৫MB');setStoryFile(f);setStoryPreview(await read(f));setStoryOpen(true)};
 const choosePosts=async(fs:FileList|null)=>{const a=Array.from(fs??[]).filter(f=>/^(image|video)\//.test(f.type));if(a.length>6)return toast.error('সর্বোচ্চ ৬টি মিডিয়া');if(a.some(f=>f.size>25*1024*1024))return toast.error('প্রতিটি ফাইল সর্বোচ্চ ২৫MB');setPostFiles(a);setPostPreview(await Promise.all(a.map(read)));setPostOpen(true)};
 const upload=async(f:File,folder:string)=>{const ext=(f.name.split('.').pop()||'bin').toLowerCase();const path=`${user!.id}/${folder}/${safeUUID()}.${ext}`;const {error}=await (supabase as any).storage.from('community-media').upload(path,f,{upsert:false,contentType:f.type,cacheControl:'31536000'});if(error)throw error;return(supabase as any).storage.from('community-media').getPublicUrl(path).data.publicUrl};
 const publishStory=async()=>{if(!user)return;if(!storyFile&&!storyText.trim())return toast.error('ছবি/ভিডিও বা লেখা যোগ করুন');setPosting(true);try{const url=storyFile?await upload(storyFile,'stories'):null;const body=storyText.trim()+(storyFile&&storyText.trim()?`\n[TEXT_POS:${storyPos}]`:'');const {error}=await(supabase as any).from('social_stories').insert({user_id:user.id,author_name:displayName,author_avatar:profile?.avatar_url||null,body:body||null,image_url:url});if(error)throw error;toast.success('Story যোগ হয়েছে');closeStory()}catch(e:any){toast.error(e?.message||'Story আপলোড ব্যর্থ')}finally{setPosting(false)}};
 const publishPost=async()=>{if(!user)return;if(!postText.trim()&&!postFiles.length)return toast.error('কিছু লিখুন বা মিডিয়া দিন');setPosting(true);try{const urls=await Promise.all(postFiles.map(f=>upload(f,'posts')));const {error}=await(supabase as any).from('social_posts').insert({user_id:user.id,author_name:displayName,author_avatar:profile?.avatar_url||null,body:postText.trim(),image_urls:urls});if(error)throw error;toast.success('পোস্ট প্রকাশিত হয়েছে');setPostText('');setPostFiles([]);setPostPreview([]);setPostOpen(false)}catch(e:any){toast.error(e?.message||'আপলোড ব্যর্থ')}finally{setPosting(false)}};
 const closeStory=()=>{setStoryOpen(false);setStoryFile(null);setStoryPreview('');setStoryText('');setStoryPos(50)};
 return <div className="min-h-screen bg-[#f4f6f5] pb-8"><main className="mx-auto max-w-2xl">
  <section className="border-b bg-background px-3 py-2.5 sm:mt-2 sm:rounded-2xl sm:border"><div className="flex gap-2.5 overflow-x-auto [scrollbar-width:none]"><button onClick={openStory} className="group w-[76px] shrink-0 overflow-hidden rounded-2xl border bg-background shadow-sm"><div className="relative flex h-[96px] items-center justify-center bg-gradient-to-br from-brand-light to-background"><div className="h-11 w-11 overflow-hidden rounded-full border-2 border-white shadow">{profile?.avatar_url?<img src={profile.avatar_url} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center bg-brand text-white font-black">{displayName.slice(0,1)}</div>}</div><span className="absolute bottom-2 right-2 flex h-6 w-6 items-center justify-center rounded-full bg-brand text-white ring-2 ring-white"><Plus className="h-4 w-4"/></span></div><b className="block py-1.5 text-[10px]">Story যোগ</b></button><div className="flex items-center text-[9px] font-bold text-muted-foreground">আপনার বাগানের গল্প ও অনুপ্রেরণা 🌱</div></div></section>
  <section className="border-b bg-background px-3 py-2.5 sm:mt-2 sm:rounded-2xl sm:border"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="কমিউনিটিতে খুঁজুন..." className="h-9 w-full rounded-full bg-muted pl-9 pr-3 text-[11px] outline-none focus:ring-2 focus:ring-brand/15"/></div><div className="mt-2 flex gap-1 overflow-x-auto [scrollbar-width:none]">{tabs.map(([id,label,I])=><button key={id} onClick={()=>setTab(id)} className={`flex h-8 shrink-0 items-center gap-1.5 rounded-full px-3 text-[10px] font-black transition ${tab===id?'bg-brand text-white shadow-sm':'bg-muted text-muted-foreground'}`}><I className="h-3.5 w-3.5"/>{label}</button>)}</div></section>
  {isLoggedIn&&<section className="border-b bg-background px-3 py-2.5 sm:mt-2 sm:rounded-2xl sm:border"><button onClick={()=>setPostOpen(true)} className="flex w-full items-center gap-2 text-left"><div className="h-9 w-9 overflow-hidden rounded-full bg-brand-light">{profile?.avatar_url?<img src={profile.avatar_url} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-brand font-black">{displayName.slice(0,1)}</div>}</div><span className="flex-1 rounded-full bg-muted px-3 py-2 text-[11px] text-muted-foreground">{displayName}, আজ কী শেয়ার করবেন?</span></button><div className="mt-2 flex border-t pt-1.5"><button onClick={()=>postInput.current?.click()} className="flex flex-1 items-center justify-center gap-1.5 rounded-lg py-1.5 text-[10px] font-black text-muted-foreground"><ImageIcon className="h-4 w-4 text-brand"/>ছবি / ভিডিও</button><input ref={postInput} hidden type="file" accept="image/*,video/*" multiple onChange={e=>void choosePosts(e.target.files)}/><button onClick={()=>setPostOpen(true)} className="rounded-full bg-brand px-4 py-1.5 text-[10px] font-black text-white">পোস্ট করুন</button></div></section>}
  <section className="mt-2 rounded-2xl border bg-background p-8 text-center"><Users className="mx-auto h-7 w-7 text-brand"/><b className="mt-2 block text-xs">কমিউনিটি ফিড</b><p className="mt-1 text-[10px] text-muted-foreground">নিউজ ফিড, ভিডিও, এক্সপ্লোর ও সেরা পোস্ট এখানে দেখাবে।</p></section>
 </main>
 {storyOpen&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-3 backdrop-blur-sm"><div className="w-full max-w-sm overflow-hidden rounded-3xl bg-background shadow-2xl"><div className="flex items-center justify-between border-b px-4 py-3"><div><b className="text-sm">Story তৈরি করুন</b><p className="text-[9px] text-muted-foreground">Gallery → Preview → Text → Share</p></div><button onClick={closeStory}><X className="h-5 w-5"/></button></div><div className="p-3"><button onClick={openStory} className="relative flex aspect-[9/14] w-full items-center justify-center overflow-hidden rounded-2xl bg-neutral-900">{storyPreview?(isVideo(storyFile)?<video src={storyPreview} controls playsInline className="h-full w-full object-contain"/>:<img src={storyPreview} className="h-full w-full object-contain"/>):<div className="text-center text-white"><Plus className="mx-auto h-10 w-10 rounded-full bg-brand p-2"/><b className="mt-2 block text-xs">Gallery খুলুন</b></div>}{storyText&&<span style={{top:`${storyPos}%`}} className="absolute left-3 right-3 -translate-y-1/2 rounded-lg bg-black/50 px-2 py-1 text-center text-sm font-black text-white">{storyText}</span>}</button><input ref={storyInput} hidden type="file" accept="image/*,video/*" onChange={e=>void chooseStory(e.target.files)}/><div className="mt-2 rounded-2xl bg-muted p-2.5"><div className="flex items-center gap-2"><Type className="h-4 w-4 text-brand"/><input value={storyText} onChange={e=>setStoryText(e.target.value)} placeholder="ছবির উপর টেক্সট লিখুন..." className="flex-1 bg-transparent text-xs outline-none"/></div>{storyText&&<div className="mt-2"><div className="mb-1 flex justify-between text-[8px] text-muted-foreground"><span>টেক্সট সরানো / নড়ানো</span><span>{Math.round(storyPos)}%</span></div><input type="range" min="10" max="90" value={storyPos} onChange={e=>setStoryPos(Number(e.target.value))} className="w-full accent-brand"/></div>}</div><button disabled={posting} onClick={()=>void publishStory()} className="mt-2 flex w-full items-center justify-center gap-2 rounded-2xl bg-brand py-3 text-xs font-black text-white">{posting?<><Loader2 className="h-4 w-4 animate-spin"/>আপলোড হচ্ছে...</>:<><Send className="h-4 w-4"/>Story শেয়ার করুন</>}</button></div></div></div>}
 {postOpen&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-3"><div className="w-full max-w-md rounded-t-3xl bg-background p-4 sm:rounded-3xl"><div className="flex items-center justify-between"><b className="text-sm">পোস্ট তৈরি করুন</b><button onClick={()=>setPostOpen(false)}><X className="h-5 w-5"/></button></div><textarea autoFocus value={postText} onChange={e=>setPostText(e.target.value)} rows={3} placeholder={`${displayName}, আজ কী শেয়ার করবেন?`} className="mt-3 w-full resize-none rounded-2xl bg-muted p-3 text-sm outline-none"/><div className="mt-2 grid grid-cols-3 gap-1.5">{postPreview.map((u,i)=>isVideo(postFiles[i])?<video key={u} src={u} controls className="h-24 w-full rounded-xl object-cover"/>:<img key={u} src={u} className="h-24 w-full rounded-xl object-cover"/>)}</div><div className="mt-3 flex items-center justify-between"><button onClick={()=>postInput.current?.click()} className="flex items-center gap-1.5 rounded-xl bg-muted px-3 py-2 text-[10px] font-black"><ImageIcon className="h-4 w-4 text-brand"/>ছবি / ভিডিও</button><button disabled={posting} onClick={()=>void publishPost()} className="rounded-full bg-brand px-5 py-2 text-[10px] font-black text-white">{posting?<Loader2 className="h-4 w-4 animate-spin"/>:'পোস্ট করুন'}</button></div></div></div>}
 </div>
}
