import { Link } from "@tanstack/react-router";
import { useMemo, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, ChevronLeft, ChevronRight, Compass, Heart, Image as ImageIcon, Loader2, MessageCircle, Play, Plus, Search, Send, Share2, ShoppingCart, Trophy, Users, Video, X } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/lib/personal-supabase/client";
import { useCustomer } from "@/lib/customer-account";
import { useCart } from "@/lib/cart-store";

type Post={id:string;user_id:string|null;author_name:string;author_avatar:string|null;body:string;image_urls:string[];like_count:number;comment_count:number;created_at:string};
type Story={id:string;user_id:string|null;author_name:string;author_avatar:string|null;body:string|null;image_url:string|null;created_at:string;expires_at:string};
type Reaction={post_id:string;user_id:string;reaction:string};
const R=[['like','👍'],['love','❤️'],['haha','😂'],['wow','😮'],['sad','😢'],['angry','😡']] as const;
const T=[['feed','নিউজ ফিড',Users],['videos','ভিডিও',Play],['explore','এক্সপ্লোর',Compass],['top','সেরা',Trophy]] as const;
const ago=(s:string)=>{const d=(Date.now()-new Date(s).getTime())/1000;return d<60?'এইমাত্র':d<3600?`${Math.floor(d/60)} মিনিট আগে`:d<86400?`${Math.floor(d/3600)} ঘণ্টা আগে`:new Date(s).toLocaleDateString('bn-BD',{day:'numeric',month:'short'})};
const vid=(x:string)=>/^(data:video\/)|\.(mp4|webm|mov|m4v)(\?|$)/i.test(x);
function Avatar({name,src,sm=false}:{name:string;src?:string|null;sm?:boolean}){return src?<img src={src} alt="" className={`${sm?'h-8 w-8':'h-10 w-10'} shrink-0 rounded-full object-cover`}/>:<div className={`${sm?'h-8 w-8 text-xs':'h-10 w-10'} shrink-0 rounded-full bg-brand-light text-brand font-black flex items-center justify-center`}>{name?.slice(0,1)||'🌱'}</div>}

export function SocialFeedPro(){
 const {user,isLoggedIn,displayName,profile}=useCustomer(); const qc=useQueryClient(); const cart=useCart(s=>s.count());
 const storyPicker=useRef<HTMLInputElement>(null),postPicker=useRef<HTMLInputElement>(null);
 const [storyOpen,setStoryOpen]=useState(false),[storyIndex,setStoryIndex]=useState<number|null>(null),[storyFile,setStoryFile]=useState<File|null>(null),[storyPreview,setStoryPreview]=useState(''),[storyText,setStoryText]=useState('');
 const [postText,setPostText]=useState(''),[postFiles,setPostFiles]=useState<File[]>([]),[postPreview,setPostPreview]=useState<string[]>([]),[busy,setBusy]=useState(false),[tab,setTab]=useState('feed'),[q,setQ]=useState(''),[reaction,setReaction]=useState<string|null>(null),[commentPost,setCommentPost]=useState<string|null>(null),[commentText,setCommentText]=useState('');
 const posts=useQuery({queryKey:['community-posts'],queryFn:async()=>{const {data,error}=await (supabase as any).from('social_posts').select('id,user_id,author_name,author_avatar,body,image_urls,like_count,comment_count,created_at').eq('status','approved').order('created_at',{ascending:false}).limit(80);if(error)throw error;return(data??[])as Post[]},staleTime:10000});
 const stories=useQuery({queryKey:['community-stories'],queryFn:async()=>{const {data,error}=await (supabase as any).from('social_stories').select('id,user_id,author_name,author_avatar,body,image_url,created_at,expires_at').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(40);if(error)throw error;return(data??[])as Story[]},staleTime:10000});
 const rx=useQuery({queryKey:['community-reactions',posts.data?.map(p=>p.id).join(',')],enabled:!!posts.data?.length,queryFn:async()=>{const {data}=await (supabase as any).from('social_post_reactions').select('post_id,user_id,reaction').in('post_id',(posts.data??[]).map(p=>p.id));return(data??[])as Reaction[]}});
 const visible=useMemo(()=>{let a=[...(posts.data??[])];if(q.trim())a=a.filter(p=>`${p.author_name} ${p.body}`.toLowerCase().includes(q.toLowerCase()));if(tab==='videos')a=a.filter(p=>p.image_urls?.some(vid));if(tab==='top')a.sort((a,b)=>(b.like_count+b.comment_count)-(a.like_count+a.comment_count));return a},[posts.data,q,tab]);
 const fileData=(f:File)=>new Promise<string>((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(f)});
 const pickStory=async(fs:FileList|null)=>{const f=fs?.[0];if(!f)return;if(!/^(image|video)\//.test(f.type))return toast.error('শুধু ছবি বা ভিডিও নির্বাচন করুন');if(f.size>25*1024*1024)return toast.error('সর্বোচ্চ ২৫MB ফাইল দিন');setStoryFile(f);setStoryPreview(await fileData(f));setStoryOpen(true)};
 const pickPost=async(fs:FileList|null)=>{const a=Array.from(fs??[]).filter(f=>/^(image|video)\//.test(f.type));if(a.length>6)return toast.error('সর্বোচ্চ ৬টি মিডিয়া');if(a.some(f=>f.size>25*1024*1024))return toast.error('প্রতিটি ফাইল সর্বোচ্চ ২৫MB');setPostFiles(a);setPostPreview(await Promise.all(a.map(fileData)))};
 const upload=async(f:File,folder:string)=>{const ext=(f.name.split('.').pop()||'bin').toLowerCase(),path=`${user!.id}/${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await (supabase as any).storage.from('community-media').upload(path,f,{upsert:false,contentType:f.type,cacheControl:'31536000'});if(error)throw error;return(supabase as any).storage.from('community-media').getPublicUrl(path).data.publicUrl as string};
 const publishStory=async()=>{if(!user)return toast.error('Story দিতে লগইন করুন');if(!storyFile&&!storyText.trim())return toast.error('Story-তে কিছু যোগ করুন');setBusy(true);try{const url=storyFile?await upload(storyFile,'stories'):null;const {error}=await (supabase as any).from('social_stories').insert({user_id:user.id,author_name:displayName,author_avatar:profile?.avatar_url||null,body:storyText.trim()||null,image_url:url});if(error)throw error;toast.success('Story যোগ হয়েছে');setStoryOpen(false);setStoryFile(null);setStoryPreview('');setStoryText('');qc.invalidateQueries({queryKey:['community-stories']})}catch(e:any){toast.error(e?.message||'Story আপলোড ব্যর্থ')}finally{setBusy(false)}};
 const publishPost=async()=>{if(!user)return toast.error('পোস্ট করতে লগইন করুন');if(!postText.trim()&&!postFiles.length)return toast.error('কিছু লিখুন বা মিডিয়া দিন');setBusy(true);try{const urls=await Promise.all(postFiles.map(f=>upload(f,'posts')));const {error}=await (supabase as any).from('social_posts').insert({user_id:user.id,author_name:displayName,author_avatar:profile?.avatar_url||null,body:postText.trim(),image_urls:urls});if(error)throw error;toast.success('পোস্ট প্রকাশিত হয়েছে');setPostText('');setPostFiles([]);setPostPreview([]);qc.invalidateQueries({queryKey:['community-posts']})}catch(e:any){toast.error(e?.message||'আপলোড ব্যর্থ')}finally{setBusy(false)}};
 const doReact=async(p:Post,r:string)=>{if(!user)return toast.error('রিয়েক্ট করতে লগইন করুন');const mine=rx.data?.find(x=>x.post_id===p.id&&x.user_id===user.id);const x=mine?(mine.reaction===r?(supabase as any).from('social_post_reactions').delete().eq('post_id',p.id).eq('user_id',user.id):(supabase as any).from('social_post_reactions').update({reaction:r}).eq('post_id',p.id).eq('user_id',user.id)):(supabase as any).from('social_post_reactions').insert({post_id:p.id,user_id:user.id,reaction:r});const {error}=await x;if(error)toast.error(error.message);setReaction(null);qc.invalidateQueries({queryKey:['community-reactions']});qc.invalidateQueries({queryKey:['community-posts']})};
 return <div className="min-h-screen bg-[#f3f5f4] pb-10"><header className="sticky top-0 z-50 border-b bg-background/95 px-3 py-2 shadow-sm backdrop-blur-xl"><div className="mx-auto flex max-w-2xl items-center gap-2"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-brand-light text-brand"><Users className="h-5 w-5"/></div><div className="flex-1"><b className="text-lg">কমিউনিটি <span className="text-brand">ফিড</span></b><p className="text-[9px] text-muted-foreground">বাগানিদের গল্প ও অনুপ্রেরণা 🌱</p></div><Bell className="mr-1 h-5 w-5 text-muted-foreground"/><Link to="/cart" className="relative flex h-9 items-center gap-1 rounded-full bg-brand px-3 text-xs font-black text-white"><ShoppingCart className="h-4 w-4"/>অর্ডার{cart>0&&<span className="absolute -right-1 -top-1 rounded-full bg-foreground px-1.5 text-[9px] text-background">{cart}</span>}</Link></div></header><main className="mx-auto max-w-2xl">
 <section className="border-b bg-background px-3 py-3 sm:mt-2 sm:rounded-2xl sm:border"><div className="mb-2 flex justify-between"><b className="text-sm">স্টোরি</b><button onClick={()=>isLoggedIn?setStoryOpen(true):toast.error('Story দিতে লগইন করুন')} className="text-xs font-bold text-brand">+ Story যোগ করুন</button></div><div className="flex gap-2 overflow-x-auto [scrollbar-width:none]"><button onClick={()=>isLoggedIn?setStoryOpen(true):toast.error('Story দিতে লগইন করুন')} className="w-[78px] shrink-0 overflow-hidden rounded-2xl border"><div className="relative flex h-24 items-center justify-center bg-gradient-to-br from-brand-light to-background"><Avatar name={displayName} src={profile?.avatar_url}/><span className="absolute bottom-2 right-2 flex h-6 w-6 items-center justify-center rounded-full bg-brand text-white"><Plus className="h-4 w-4"/></span></div><span className="block py-1.5 text-[10px] font-black">আপনার Story</span></button>{(stories.data??[]).map((s,i)=><button key={s.id} onClick={()=>setStoryIndex(i)} className="w-[78px] shrink-0 overflow-hidden rounded-2xl border"><div className="relative h-24 overflow-hidden bg-muted">{s.image_url?(vid(s.image_url)?<video src={s.image_url} muted playsInline className="h-full w-full object-cover"/>:<img src={s.image_url} alt="" className="h-full w-full object-cover"/>):<div className="flex h-full items-center justify-center p-2 text-center text-[10px] font-bold">{s.body||'🌱'}</div>}<div className="absolute left-1 top-1 rounded-full bg-background p-0.5 ring-2 ring-brand"><Avatar name={s.author_name} src={s.author_avatar} sm/></div>{s.image_url&&vid(s.image_url)&&<Video className="absolute bottom-1 right-1 h-4 w-4 text-white drop-shadow"/>}</div><span className="block truncate px-1 py-1.5 text-[10px] font-black">{s.author_name}</span></button>)}</div></section>
 <section className="border-b bg-background px-3 py-3 sm:mt-2 sm:rounded-2xl sm:border"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="কমিউনিটিতে খুঁজুন..." className="w-full rounded-full bg-muted py-2.5 pl-9 pr-3 text-xs outline-none"/></div><div className="mt-3 flex gap-1 overflow-x-auto">{T.map(([id,l,I])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-1.5 rounded-full px-3 py-2 text-[11px] font-bold ${tab===id?'bg-brand text-white':'bg-muted text-muted-foreground'}`}><I className="h-3.5 w-3.5"/>{l}</button>)}</div></section>
 {isLoggedIn&&<section className="border-b bg-background px-3 py-3 sm:mt-2 sm:rounded-2xl sm:border"><div className="flex gap-2"><Avatar name={displayName} src={profile?.avatar_url}/><textarea value={postText} onChange={e=>setPostText(e.target.value)} rows={2} placeholder={`${displayName}, আজ কী শেয়ার করবেন?`} className="flex-1 resize-none rounded-2xl bg-muted p-3 text-sm outline-none"/></div>{postPreview.length>0&&<div className="mt-2 grid grid-cols-3 gap-2">{postPreview.map((u,i)=>vid(postFiles[i]?.type||'')?<video key={u} src={u} controls className="h-24 w-full rounded-xl object-cover"/>:<img key={u} src={u} alt="" className="h-24 w-full rounded-xl object-cover"/>)}</div>}<div className="mt-2 flex items-center justify-between border-t pt-2"><button onClick={()=>postPicker.current?.click()} className="flex items-center gap-1.5 rounded-xl px-2 py-2 text-xs font-bold text-muted-foreground"><ImageIcon className="h-5 w-5 text-brand"/>ছবি / ভিডিও</button><input ref={postPicker} hidden type="file" accept="image/*,video/*" multiple onChange={e=>void pickPost(e.target.files)}/><button disabled={busy} onClick={()=>void publishPost()} className="rounded-full bg-brand px-5 py-2 text-xs font-black text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:'পোস্ট করুন'}</button></div></section>}
 <div className="space-y-2 sm:mt-2">{visible.map(p=>{const mine=rx.data?.find(r=>r.post_id===p.id&&r.user_id===user?.id)?.reaction;return <article key={p.id} className="border-b bg-background px-3 py-3 sm:rounded-2xl sm:border"><div className="flex gap-2.5"><Avatar name={p.author_name} src={p.author_avatar}/><div className="min-w-0 flex-1"><b className="text-sm">{p.author_name}</b><div className="text-[10px] text-muted-foreground">{ago(p.created_at)} · 🌱</div><p className="mt-2 whitespace-pre-wrap text-[14px] leading-6">{p.body}</p>{p.image_urls?.length>0&&<div className={`mt-2 grid gap-1 overflow-hidden rounded-2xl ${p.image_urls.length>1?'grid-cols-2':''}`}>{p.image_urls.map(u=>vid(u)?<video key={u} src={u} controls playsInline className="max-h-[430px] min-h-40 w-full bg-black object-cover"/>:<img key={u} src={u} alt="" className="max-h-[430px] min-h-40 w-full object-cover"/>)}</div>}<div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>{p.like_count} রিয়েক্ট · {p.comment_count} কমেন্ট</span></div><div className="mt-1 grid grid-cols-3 border-t"><div className="relative"><button onClick={()=>setReaction(reaction===p.id?null:p.id)} className={`flex w-full justify-center gap-1 py-2 text-xs font-bold ${mine?'text-brand':'text-muted-foreground'}`}>{mine?R.find(x=>x[0]===mine)?.[1]:'👍'} রিয়েক্ট</button>{reaction===p.id&&<div className="absolute bottom-10 left-0 z-20 flex gap-1 rounded-full border bg-background px-2 py-1.5 shadow-xl">{R.map(([r,e])=><button key={r} onClick={()=>void doReact(p,r)} className="text-xl hover:scale-125">{e}</button>)}</div>}</div><button onClick={()=>setCommentPost(commentPost===p.id?null:p.id)} className="flex justify-center gap-1 py-2 text-xs font-bold text-muted-foreground"><MessageCircle className="h-4 w-4"/>কমেন্ট</button><button onClick={()=>navigator.share?void navigator.share({text:p.body,url:location.href}):toast.success('শেয়ার করার জন্য প্রস্তুত')} className="flex justify-center gap-1 py-2 text-xs font-bold text-muted-foreground"><Share2 className="h-4 w-4"/>শেয়ার</button></div></div></div></article>})}</div></main>
 {storyOpen&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/60 sm:items-center sm:p-4"><div className="w-full max-w-md rounded-t-3xl bg-background p-4 sm:rounded-3xl"><div className="flex items-center justify-between"><div><b>নতুন Story</b><p className="text-[10px] text-muted-foreground">২৪ ঘণ্টা থাকবে · ছবি বা ভিডিও</p></div><button onClick={()=>setStoryOpen(false)}><X/></button></div><button onClick={()=>storyPicker.current?.click()} className="relative mt-3 flex aspect-[9/14] w-full items-center justify-center overflow-hidden rounded-3xl border-2 border-dashed bg-muted">{storyPreview?(storyFile&&storyFile.type.startsWith('video/')?<video src={storyPreview} controls playsInline className="h-full w-full object-cover"/>:<img src={storyPreview} alt="" className="h-full w-full object-cover"/>):<div className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-brand text-white"><Plus className="h-8 w-8"/></div><b className="mt-3 block text-sm">Gallery থেকে নির্বাচন করুন</b><p className="text-[10px] text-muted-foreground">ছবি / ভিডিও · সর্বোচ্চ ২৫MB</p></div>}<input ref={storyPicker} hidden type="file" accept="image/*,video/*" onChange={e=>void pickStory(e.target.files)}/></button><textarea value={storyText} onChange={e=>setStoryText(e.target.value)} rows={2} placeholder="Story-তে কিছু লিখুন..." className="mt-3 w-full rounded-2xl bg-muted p-3 text-sm outline-none"/><button disabled={busy} onClick={()=>void publishStory()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-brand py-3 text-sm font-black text-white">{busy?<><Loader2 className="h-4 w-4 animate-spin"/>আপলোড হচ্ছে...</>:<><CheckIcon/>Story শেয়ার করুন</>}</button></div></div>}
 {storyIndex!==null&&stories.data?.[storyIndex]&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-black p-2"><button onClick={()=>setStoryIndex(null)} className="absolute right-3 top-3 z-20 rounded-full bg-white/15 p-2 text-white"><X/></button><button disabled={storyIndex<=0} onClick={()=>setStoryIndex(i=>Math.max(0,(i??0)-1))} className="absolute left-2 z-20 rounded-full bg-white/15 p-2 text-white disabled:opacity-30"><ChevronLeft/></button><div className="relative h-[88vh] w-full max-w-md overflow-hidden rounded-3xl bg-neutral-900">{stories.data[storyIndex].image_url?(vid(stories.data[storyIndex].image_url)?<video src={stories.data[storyIndex].image_url} autoPlay controls playsInline className="h-full w-full object-contain"/>:<img src={stories.data[storyIndex].image_url} alt="" className="h-full w-full object-contain"/>):<div className="flex h-full items-center justify-center p-8 text-center text-2xl font-black text-white">{stories.data[storyIndex].body}</div>}<div className="absolute left-4 top-4 flex items-center gap-2 text-white"><Avatar name={stories.data[storyIndex].author_name} src={stories.data[storyIndex].author_avatar}/><div><b className="text-sm">{stories.data[storyIndex].author_name}</b><div className="text-[9px] opacity-70">{ago(stories.data[storyIndex].created_at)}</div></div></div></div><button disabled={storyIndex>=((stories.data?.length??1)-1)} onClick={()=>setStoryIndex(i=>Math.min((stories.data?.length??1)-1,(i??0)+1))} className="absolute right-2 rounded-full bg-white/15 p-2 text-white disabled:opacity-30"><ChevronRight/></button></div>}
 </div>;
}
function CheckIcon(){return <span className="inline-flex h-4 w-4 items-center justify-center rounded-full border-2 border-white text-[9px]">✓</span>}
