import { useNavigate } from "@tanstack/react-router";
import { landingBaseSlug } from "@/lib/landing-slug";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState, useMemo, useRef, useEffect, useCallback } from "react";
import { supabase } from "@/lib/personal-supabase/client";
import { placeOrder } from "@/lib/place-order.functions";
import { useCheckoutAutofill } from "@/lib/useCheckoutAutofill";
import { taka } from "@/lib/format";
import { toast } from "sonner";
import { Check, ShoppingCart, User, Phone, MapPin, Star, Leaf, BarChart3, Sprout, Wallet, Truck, ShieldCheck, Award, Headphones, X } from "lucide-react";
import { trackInitiateCheckout, trackPurchase } from "@/lib/fbq";
import { BrandLoader } from "@/components/layout/BrandLoader";
import { Footer } from "@/components/layout/Footer";
import { FacebookPixel } from "@/components/layout/FacebookPixel";
import { trackVisit } from "@/lib/track-visit";
import { getFbContext } from "@/lib/fb-context";
import { toImg, imgSrcSet, imgFallback } from "@/lib/img";
import brandLogoFile from "@/assets/logo.jpg";
import { mergeContent, DEFAULT_FEATURES, DEFAULT_WHY, DEFAULT_REVIEWS } from "@/lib/landing-content";
import { PHONE_ERROR, isValidBdPhone, phoneSubmitError } from "@/lib/bd-phone";

const bnNum=(n:number|string)=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[Number(d)]);
const bnTaka=(n:number)=>"৳"+bnNum(Math.round(Number(n)||0).toLocaleString("en-US"));
const DEFAULT_ICONS = [Sprout, Leaf, ShieldCheck, Award, Wallet, Truck, Headphones, BarChart3];
const LANDING_CHECKOUT_GROUP_STYLE = `
.lp-confirm-cta{position:relative;overflow:hidden;width:100%;display:inline-flex;align-items:center;justify-content:center;gap:10px;min-height:54px;padding:14px 20px;border:0;border-radius:16px;font-size:17px;font-weight:800;letter-spacing:-.01em;color:#fff;cursor:pointer;background:linear-gradient(135deg,#047857 0%,#059669 45%,#10b981 100%);box-shadow:0 14px 34px -14px rgba(4,120,87,.75),0 2px 0 0 rgba(255,255,255,.18) inset;transition:transform .18s cubic-bezier(.22,1,.36,1),box-shadow .18s ease,filter .18s ease;animation:lpConfirmRise .45s cubic-bezier(.22,1,.36,1) both}
.lp-confirm-cta::after{content:"";position:absolute;top:0;bottom:0;left:-40%;width:35%;background:linear-gradient(100deg,transparent,rgba(255,255,255,.42),transparent);transform:skewX(-18deg);animation:lpConfirmShine 2.8s ease-in-out infinite}
.lp-confirm-cta:hover{transform:translateY(-2px);box-shadow:0 20px 40px -14px rgba(4,120,87,.8)}
.lp-confirm-cta:active{transform:translateY(0) scale(.985)}
.lp-confirm-cta:disabled{opacity:.65;cursor:not-allowed;animation:none}
.lp-confirm-cta:disabled::after{display:none}
.lp-confirm-amount{font-variant-numeric:tabular-nums}
@keyframes lpConfirmShine{0%{left:-40%}55%{left:120%}100%{left:120%}}
@keyframes lpConfirmRise{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}
@media (prefers-reduced-motion:reduce){.lp-confirm-cta,.lp-confirm-cta::after{animation:none}}
.lp-product-checkout-group { border:1px solid #dfeae2; border-radius:18px; background:#fff; overflow:hidden; }
.lp-product-checkout-group .lp-checkout-shell { border-top:1px solid #dfeae2; }
.lp-product-checkout-group .lp-inline-selector { padding:8px 10px; margin:0; border-bottom:1px solid #edf3ee; background:#fff; }
.lp-product-checkout-group .lp-inline-title { font-size:11px; font-weight:800; color:#64748b; margin-bottom:6px; }
.lp-product-checkout-group .lp-inline-options { display:flex; flex-direction:column; gap:5px; }
.lp-product-checkout-group .lp-inline-option { min-height:48px; padding:6px 8px; border-radius:10px; }
.lp-product-checkout-group .lp-inline-option img { width:34px; height:34px; border-radius:8px; }
.lp-product-checkout-group .lp-inline-option .lp-option-name { font-size:12px; line-height:1.25; }
.lp-product-checkout-group .lp-inline-option .lp-option-price { font-size:13px; }
.lp-product-checkout-group .lp-inline-summary { border:0; border-top:1px solid #edf3ee; border-radius:0; }
.lp-product-checkout-group .lp-inline-summary > div { padding-top:7px; padding-bottom:7px; }
@media (max-width:640px) {
  .lp-product-checkout-group .lp-inline-selector { padding:7px 8px; }
  .lp-product-checkout-group .lp-inline-option { min-height:46px; padding:5px 7px; }
}
`;

const REF_STYLE = `

.lp-premium-header{background:rgba(255,255,255,.94);backdrop-filter:blur(10px);border-bottom:1px solid #d9efe2;box-shadow:0 2px 10px -6px rgba(6,78,59,.25)}
.lp-fancy-list{border-radius:18px;overflow:hidden;background:linear-gradient(180deg,#ffffff,#f6fffa);border:1px solid #d6efe0;box-shadow:0 14px 34px -22px rgba(6,78,59,.55)}
.lp-fancy-row{position:relative;display:flex;align-items:flex-start;gap:12px;padding:11px 14px;transition:background .25s ease,transform .25s ease}
.lp-fancy-row+.lp-fancy-row{border-top:1px solid #eaf5ee}
.lp-fancy-row:nth-child(even){background:rgba(236,253,243,.55)}
.lp-fancy-row::before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:linear-gradient(180deg,#22c55e,#0f8a4d);transform:scaleY(0);transform-origin:top;transition:transform .3s ease}
.lp-fancy-row:hover{background:#f0fdf4;transform:translateX(2px)}
.lp-fancy-row:hover::before{transform:scaleY(1)}
.lp-fancy-ico{display:grid;place-items:center;width:40px;height:40px;border-radius:12px;flex:0 0 auto;margin-top:2px;background:linear-gradient(135deg,#e9fbef,#d2f5e0);box-shadow:inset 0 0 0 1px rgba(16,122,79,.15),0 4px 10px -6px rgba(6,78,59,.5);animation:lpIcoFloat 4s ease-in-out infinite}
@keyframes lpIcoFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-2px)}}
.lp-fancy-check{color:#0f8a4d;flex:0 0 auto;margin-top:8px}
.lp-ref-band{background:linear-gradient(180deg,#CCFFD3 0%,#e6ffea 100%);margin:0 -16px 0;padding:0 10px 8px;border-radius:0 0 22px 22px}
.lp-root{max-width:100%}
.lp-hdr-timer{display:flex;flex-direction:column;align-items:flex-end;gap:2px}
.lp-hdr-timer-row{display:flex;align-items:center;gap:4px}
.lp-hdr-timer-note{font-size:9px;font-weight:800;color:#d97706;letter-spacing:.02em;line-height:1}
.lp-hdr-timer b{background:#1a8944;color:#fff;font-size:13px;font-weight:800;padding:3px 6px;border-radius:6px;min-width:28px;text-align:center;font-variant-numeric:tabular-nums;line-height:1.2}
.lp-hdr-timer i{font-style:normal;color:#1a8944;font-weight:800;font-size:13px}
.lp-hdr-timer em{font-style:normal;display:block;font-size:9px;color:#64748b;font-weight:700;text-align:center;margin-top:2px}
.lp-card{background:#fff;border:1px solid #e6efe8;border-radius:18px;box-shadow:0 20px 44px -32px rgba(6,78,59,.45)}
.top-hook{width:100%;max-width:520px;margin:0 auto;padding:16px 14px;text-align:center;background:linear-gradient(120deg,#1b4332,#2d6a4f);position:relative;color:#fff;overflow:hidden;border-bottom:5px solid #ffd700;box-shadow:0 8px 20px rgba(0,0,0,0.4);border-radius:0 0 18px 18px}
.top-hook h1{font-size:34px;font-weight:900;margin:0 0 8px 0;letter-spacing:.5px;line-height:1.25;text-shadow:0 2px 8px rgba(0,0,0,0.5)}
.top-hook h1 .hl-line{display:block}
.price-badge{display:inline-block;font-size:34px;font-weight:900;padding:8px 18px;border-radius:30px;background:linear-gradient(90deg,#ffd700,#ffb703);color:#111;box-shadow:0 6px 20px rgba(255,180,0,0.6);position:relative;animation:refPulse 1.6s infinite;line-height:1.2}
@keyframes refPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.08)}}
.top-hook .ribbon{position:absolute;top:-6px;right:-6px;background:#ff4b00;color:#fff;font-size:12px;font-weight:700;padding:4px 8px;border-radius:4px;text-transform:uppercase;box-shadow:0 2px 6px rgba(0,0,0,0.3)}
.hook-divider{width:70px;height:3px;background:linear-gradient(90deg,#ffd700,#ffb703);margin:12px auto 10px;border-radius:2px}
.hook-delivery{font-size:16px;opacity:.95;display:flex;justify-content:center;align-items:center;gap:6px}
.hook-delivery span{font-size:18px}
.lp-ref-cta{position:relative;overflow:hidden;display:flex;align-items:center;justify-content:center;gap:10px;width:100%;max-width:440px;margin:0 auto;background:linear-gradient(135deg,#ff2d20 0%,#ff0000 55%,#d40000 100%);color:#fff;border:3px solid #fff;border-radius:12px;font-size:22px;font-weight:700;padding:13px 20px;line-height:1.4;box-shadow:0 16px 34px -16px rgba(255,0,0,.85),0 2px 0 rgba(255,255,255,.25) inset;transition:transform .18s cubic-bezier(.22,1,.36,1),box-shadow .18s ease;animation:lpCtaBeat 2.6s ease-in-out infinite}
.lp-ref-cta::after{content:"";position:absolute;top:0;bottom:0;left:-45%;width:38%;background:linear-gradient(100deg,transparent,rgba(255,255,255,.45),transparent);transform:skewX(-18deg);animation:lpConfirmShine 3s ease-in-out infinite}
.lp-ref-cta:hover{transform:translateY(-2px);box-shadow:0 22px 40px -16px rgba(255,0,0,.9)}
.lp-ref-cta:active{transform:scale(.98)}
@keyframes lpCtaBeat{0%,100%{transform:scale(1)}50%{transform:scale(1.02)}}
@media(max-width:480px){.lp-ref-cta{font-size:19px;padding:12px 16px}}
.combo-table{width:100%;max-width:520px;margin:0 auto;border-collapse:separate;border-spacing:0;font-size:14px;border-radius:14px;overflow:hidden;box-shadow:0 4px 15px rgba(0,0,0,0.1);text-align:center}
.combo-table caption{caption-side:top;font-size:20px;font-weight:700;margin-bottom:12px;color:#064e3b}
.combo-table th{background:linear-gradient(135deg,#ff7043,#ffb74d);color:#fff;padding:10px 6px;font-weight:700;letter-spacing:.5px;text-shadow:0 1px 2px rgba(0,0,0,.2)}
.combo-table td{padding:8px 6px;border-bottom:1px solid #e0e0e0;color:#2c2c2c}
.combo-table tr:nth-child(odd) td{background:#e8f5e9}
.combo-table tr:nth-child(even) td{background:#fffde7}
.combo-table tr:last-child td{border-bottom:none}
@media(max-width:600px){.combo-table th,.combo-table td{padding:8px 4px;font-size:13px}}
.cute-timer-container{text-align:center;background:linear-gradient(180deg,#fffdf7,#fff4e3);border:1.5px dashed #b59441;border-radius:15px;padding:10px 15px;max-width:320px;margin:10px auto}
.timer-label{font-size:14px;color:#555;margin:0 0 5px 0;font-weight:600}
.timer-display{display:flex;justify-content:center;align-items:center;gap:8px}
.time-part{display:flex;flex-direction:column;align-items:center}
.time-part span{background:#1a8944;color:#fff;font-size:20px;font-weight:700;padding:4px 8px;border-radius:6px;min-width:35px;display:inline-block;line-height:1.2}
.time-part label{font-size:10px;color:#1a8944;font-weight:700;margin-top:3px}
.time-separator{font-size:20px;font-weight:700;color:#1a8944;margin-top:-15px}
@media(max-width:480px){.cute-timer-container{padding:8px 10px;max-width:280px}.time-part span{font-size:18px;padding:3px 6px}}
.lp-footer-wrap>footer{padding-bottom:78px}
.lp-order-note{display:flex;align-items:center;gap:8px;justify-content:center;text-align:left;background:linear-gradient(135deg,#f0fdf4,#ecfdf5);border:1px solid #bbf7d0;border-radius:14px;padding:9px 12px;font-size:12px;font-weight:600;color:#14532d;line-height:1.5;box-shadow:0 4px 14px -10px rgba(6,78,59,.5)}
.lp-order-note svg{color:#16a34a}
.lp-trust-note{background:#fff;border:3px solid #fff;border-radius:20px;box-shadow:0 64px 80px -40px rgba(0,0,0,.12);padding:24px 16px;text-align:center;font-size:13px;font-weight:600;color:#000;line-height:1.6}

.lp-agri-bg{background:#f8faf7;background-image:radial-gradient(ellipse at 50% -10%,rgba(22,163,74,.10) 0%,transparent 55%),radial-gradient(ellipse at 50% 110%,rgba(251,191,36,.08) 0%,transparent 50%),url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='72' height='72' viewBox='0 0 72 72'%3E%3Cpath d='M36 8c4 14 18 24 28 42-14-10-24 0-28 16-4-16-14-26-28-42 10-18 24-28 28-42z' fill='%2316a34a' fill-opacity='0.035'/%3E%3C/svg%3E");}
.lp-agri-bg .lp-card,.lp-agri-bg .combo-table,.lp-agri-bg .lp-product-checkout-group{background:#fff}
`;
function IconRowList({items,themeColor,themeBg10}:{items:{title:string;text?:string;icon?:string}[];themeColor:string;themeBg10:string}){return <div className="lp-fancy-list">{items.map((it,i)=>{const Icon=DEFAULT_ICONS[i%DEFAULT_ICONS.length];return <div key={i} className="lp-fancy-row" style={{animationDelay:`${i*120}ms`}}><span className="lp-fancy-ico" style={{color:themeColor}}>{it.icon?<span className="text-lg leading-none">{it.icon}</span>:<Icon className="w-[19px] h-[19px]"/>}</span><div className="flex-1 min-w-0"><div className="font-extrabold text-[15.5px] leading-snug text-slate-900 tracking-tight">{it.title}</div>{it.text&&<div className="text-[13px] text-slate-500 mt-1 leading-relaxed">{it.text}</div>}</div><Check className="w-[18px] h-[18px] lp-fancy-check" strokeWidth={3}/></div>})}</div>}
type Addon={product_id?:string;name:string;price:number;image?:string;old_price?:number;badge?:string;delivery_fee?:number|null};
type SiteSettings={site_name?:string;tagline?:string;logo_url?:string};
type PaymentMethod={id:string;label:string;description:string};
export function CleanLandingPage({slug}:{slug:string}){
 const navigate=useNavigate(); const runPlaceOrder=useServerFn(placeOrder); const [submitting,setSubmitting]=useState(false); const [selectedPkg,setSelectedPkg]=useState(0); const [selectedPayment,setSelectedPayment]=useState("cod"); const [form,setForm]=useState({name:"",phone:"",address:"",note:""}); const [formInView,setFormInView]=useState(false); const [phoneErr,setPhoneErr]=useState("");
 const orderSectionRef=useRef<HTMLElement|null>(null); const phoneRef=useRef<HTMLInputElement|null>(null);
 const {data:page,isLoading}=useQuery({queryKey:["landing-clean",slug],queryFn:async()=>(await supabase.from("landing_pages").select("*, products(*)").eq("slug",slug).eq("is_published",true).maybeSingle()).data});
 const {data:settingsRow}=useQuery({queryKey:["site-settings-public"],queryFn:async()=>(await supabase.from("site_settings").select("settings").maybeSingle()).data}); const settings=(settingsRow?.settings as SiteSettings)??{};
 const asArr=<T,>(v:unknown):T[]=>Array.isArray(v)?v as T[]:[]; const product=(page?.products??null) as {id:string;name:string;price:number;sale_price:number|null;images:string[]|null}|null; const rawFeatures=asArr<Feature>(page?.features); const rawWhy=asArr<WhyItem>((page as {why_choose_us?:unknown}|null)?.why_choose_us); const rawReviews=asArr<Review>(page?.reviews); const features=rawFeatures.length?rawFeatures:DEFAULT_FEATURES; const why=rawWhy.length?rawWhy:DEFAULT_WHY; const reviews=rawReviews.length?rawReviews:DEFAULT_REVIEWS; const addons=asArr<Addon>(page?.addons);
 const heroImage=page?.hero_image||product?.images?.[0]||"/placeholder.svg"; const price=(page?.sale_price??product?.sale_price??page?.regular_price??product?.price??0) as number; const regular=(page?.regular_price??product?.price??null) as number|null; const themeColor=(page?.theme_color as string)||"#16a34a"; const themeBg10=themeColor+"1A"; const themeBg05=themeColor+"0D";
 type Pkg={label:string;price:number;old?:number|null;image?:string;badge?:string;product_id?:string;name:string;delivery_fee:number}; const defaultDelivery=Number((page as {main_delivery_fee?:number|null}|null)?.main_delivery_fee??page?.delivery_inside??70);
 const packages:Pkg[]=useMemo(()=>{const list:Pkg[]=[];if(product)list.push({label:product.name,name:product.name,price,old:regular,image:heroImage,product_id:product.id,delivery_fee:defaultDelivery});addons.forEach(a=>list.push({label:a.name,name:a.name,price:a.price,old:a.old_price,image:a.image,badge:a.badge,product_id:a.product_id,delivery_fee:a.delivery_fee==null?defaultDelivery:Number(a.delivery_fee)}));return list},[product,addons,price,regular,heroImage,defaultDelivery]);
 const selected=packages[selectedPkg]||packages[0]; const subtotal=selected?selected.price:price; const deliveryFee=selected?selected.delivery_fee:defaultDelivery; const total=subtotal+deliveryFee; const paymentMethods:PaymentMethod[]=[{id:"cod",label:"ক্যাশ অন ডেলিভারি",description:"পণ্য হাতে পেয়ে পেমেন্ট করুন"}];
 const scrollToOrder=()=>{const el=orderSectionRef.current;if(!el)return;const target=(el.querySelector(".lp-order-note") as HTMLElement|null)??el;const stickyHeader=document.querySelector<HTMLElement>(".sticky.top-0");const headerOffset=stickyHeader?.offsetHeight??0;const top=target.getBoundingClientRect().top+window.scrollY-headerOffset-12;window.scrollTo({top:Math.max(top,0),behavior:"smooth"})};
 const firedICRef=useRef(false); useEffect(()=>{const el=orderSectionRef.current;if(!el||typeof IntersectionObserver==="undefined")return;const obs=new IntersectionObserver(([entry])=>{const visible=entry.isIntersecting&&entry.intersectionRatio>0.15;setFormInView(visible);if(visible&&!firedICRef.current&&selected?.product_id){firedICRef.current=true;trackInitiateCheckout([{id:selected.product_id,name:selected.name,price:selected.price,quantity:1}],total)}},{threshold:[0,0.15,0.5,1]});obs.observe(el);return()=>obs.disconnect()},[selected?.product_id,selected?.name,selected?.price,total]);
 useCheckoutAutofill({form,setForm:updater=>setForm(f=>updater(f) as typeof f),items:selected?[{id:selected.product_id||`addon-${selectedPkg}`,name:selected.name,price:selected.price,quantity:1}]:[],subtotal,total,deliveryFee});
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const phoneValidationError=phoneSubmitError(form.phone);if(phoneValidationError){setPhoneErr(phoneValidationError);toast.error(phoneValidationError);phoneRef.current?.focus();phoneRef.current?.scrollIntoView({behavior:"smooth",block:"center"});return}setPhoneErr("");if(!form.name||!form.phone||!form.address)return toast.error("সব তথ্য পূরণ করুন");if(!selected)return toast.error("প্যাকেজ নির্বাচন করুন");setSubmitting(true);try{const itemId=selected.product_id||`addon-${selectedPkg}`;const items=[{id:itemId,name:selected.name,price:selected.price,quantity:1}];const fbCtx=getFbContext();const order=await runPlaceOrder({data:{customer_name:form.name,customer_phone:form.phone.replace(/[\s-]/g,""),customer_address:form.address,delivery_fee:deliveryFee,items,notes:form.note||null,...fbCtx}});trackPurchase(items.map(i=>({id:String(i.id),name:i.name,price:i.price,quantity:1})),total,order.id);toast.success("অর্ডার সফল!");navigate({to:"/order/$id",params:{id:order.id}})}catch(err){const msg=err instanceof Error?err.message:"অর্ডার করতে সমস্যা হয়েছে";if(msg.includes("Invalid Bangladesh mobile number")||msg.includes("01XXXXXXXXX")){setPhoneErr(PHONE_ERROR);phoneRef.current?.focus();phoneRef.current?.scrollIntoView({behavior:"smooth",block:"center"})}else{toast.error(msg)}setSubmitting(false)}};
 if(isLoading)return <div className="min-h-screen flex items-center justify-center"><BrandLoader/></div>; if(!page)return <div className="min-h-screen flex items-center justify-center text-muted-foreground">পেজ পাওয়া যায়নি</div>;
 const topBarText=(page as {top_bar_text?:string}).top_bar_text; const cta=page.cta_text||"এখনই অর্ডার করুন"; const brandName=settings.site_name||"Sheikh Seeds"; const brandLogo=settings.logo_url||brandLogoFile; const ctaStyle:React.CSSProperties={background:themeColor}; const discount=regular&&regular>price?Math.round(((regular-price)/regular)*100):0; const avgRating=reviews.length?(reviews.reduce((s,r)=>s+(Number(r.rating)||5),0)/reviews.length).toFixed(1):"5.0"; const C=mergeContent((page as {planting_steps?:unknown}|null)?.planting_steps); const seedTable=asArr<SeedRow>((page as {seed_table?:unknown}|null)?.seed_table); const seeds:SeedRow[]=seedTable.length?seedTable:C.seed_table;
 const RedCta=({label}:{label?:string})=><button onClick={scrollToOrder} className="lp-ref-cta"><ShoppingCart className="w-5 h-5 shrink-0"/>{label||C.red_cta_text||"অর্ডার করতে ক্লিক করুন"}</button>;
  const SectionHead=({kicker,title}:{kicker:string;title:string})=><div className="mb-2 text-center"><h2 className="text-[22px] sm:text-[26px] font-extrabold text-slate-900 tracking-tight">{title}</h2><span className="mt-2.5 inline-block h-1 w-14 rounded-full" style={{background:themeColor}}/></div>;
 return <div className={`lp-root min-h-screen text-slate-700 ${landingBaseSlug(slug) === "seedcombo"?"lp-agri-bg":"bg-white"}`} style={{["--lp" as string]:themeColor}}><FacebookPixel eager/><style>{LANDING_CHECKOUT_GROUP_STYLE}</style><style>{REF_STYLE}</style><LandingVisitTracker slug={slug}/>
 {C.show_popup&&<WelcomePopup themeColor={themeColor} logo={brandLogo} brand={brandName} title={C.popup_title} text={C.popup_text} cta={C.popup_cta} mode={landingBaseSlug(slug) === "seedcombo"?C.popup_mode:"text"} image={landingBaseSlug(slug) === "seedcombo"?C.popup_image:""} delay={Number(C.popup_delay)||0} onCta={scrollToOrder}/>} 

 <header className="lp-premium-header sticky top-0 z-30"><div className="container mx-auto px-3 max-w-xl py-1 flex items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><img src={toImg(brandLogo)} alt={brandName} width={28} height={28} decoding="async" className="h-7 w-7 shrink-0 rounded-full object-cover ring-1 ring-emerald-200 bg-white"/><div className="leading-tight min-w-0"><div className="font-extrabold text-[14px] text-slate-900 tracking-tight truncate">{brandName}</div>{settings.tagline&&<div className="text-[9px] text-slate-500 truncate">{settings.tagline}</div>}</div></div>{C.show_countdown!==false&&<Countdown themeColor={themeColor} hours={C.countdown_hours} title={C.countdown_title} compact/>}</div></header>
  <div className="container mx-auto px-4 pt-0 pb-2 max-w-xl space-y-3">
 <Reveal><div className="lp-ref-band"><div className="top-hook"><h1>{(()=>{const w=String(page.hero_title||page.title).trim().split(/\s+/);return w.length>2?<><span className="hl-line">{w.slice(0,2).join(" ")}</span><span className="hl-line">{w.slice(2).join(" ")}</span></>:(page.hero_title||page.title)})()}</h1><div className="price-badge">{C.price_prefix} {bnTaka(price)}{C.offer_badge_text&&<div className="ribbon">{C.offer_badge_text}</div>}</div><div className="hook-divider"/>{C.hero_note&&<div className="hook-delivery"><span>🏠</span>{C.hero_note}</div>}</div></div></Reveal>
 <div className="-mt-4"><RedCta/></div>
 <Reveal><div className="rounded-2xl border-[3px] border-white bg-white overflow-hidden shadow-[0_6px_24px_-12px_rgba(6,78,59,0.35)]"><img src={toImg(heroImage,{w:900,q:82})} srcSet={imgSrcSet(heroImage,[400,600,800,1000])} sizes="(max-width: 768px) 100vw, 640px" alt={page.title} width={900} height={900} fetchPriority="high" decoding="async" onError={e=>imgFallback(e,heroImage)} className="w-full aspect-square object-cover"/></div>{page.hero_subtitle&&<p className="text-center text-[14px] text-slate-600 leading-relaxed mt-3">{page.hero_subtitle}</p>}</Reveal>
 {C.gallery_images.length>0&&<Reveal><div className="space-y-3">{C.gallery_images.map((g,i)=><img key={g+i} src={toImg(g,{w:900,q:80})} alt={`${page.title} ${i+1}`} loading="lazy" decoding="async" onError={e=>imgFallback(e,g)} className="w-full rounded-2xl border-[3px] border-white object-cover shadow-[0_6px_24px_-12px_rgba(6,78,59,0.35)]"/>)}</div></Reveal>}
 {(C.gift_title_1||C.gift_title_2||C.gift_image)&&<Reveal>{C.gift_cta_text&&<RedCta label={C.gift_cta_text}/>}<div className="mt-4 rounded-2xl bg-white border border-emerald-100 p-4 text-center"><div className="text-[20px] sm:text-[24px] font-extrabold text-emerald-800 leading-snug">{C.gift_title_1} <span className="text-orange-600">{C.gift_title_2}</span></div>{C.gift_subtitle&&<p className="text-[13px] text-slate-500 mt-1.5">{C.gift_subtitle}</p>}{C.gift_image&&<img src={toImg(C.gift_image,{w:800,q:80})} alt={`${C.gift_title_1} ${C.gift_title_2}`.trim()} width={800} height={800} loading="lazy" decoding="async" onError={e=>imgFallback(e,C.gift_image)} className="mt-3 w-full rounded-xl object-cover"/>}{C.gift_bullets.length>0&&<div className="grid grid-cols-2 gap-2 mt-3 text-left">{C.gift_bullets.map(t=><div key={t} className="flex items-start gap-1.5 rounded-lg bg-emerald-50/70 px-2.5 py-2"><Check className="w-3.5 h-3.5 mt-0.5 shrink-0 text-emerald-600" strokeWidth={3}/><span className="text-[12px] font-medium text-emerald-900 leading-snug">{t}</span></div>)}</div>}</div></Reveal>}
 <Reveal><table className="combo-table"><caption>{C.seed_title}</caption><tbody><tr><th>{C.seed_col_1}</th><th>{C.seed_col_2}</th></tr>{seeds.map((sd,i)=><tr key={sd.name+i}><td>{sd.name}</td><td>{sd.qty}</td></tr>)}</tbody></table></Reveal>
 <RedCta/>
 {features.length>0&&<Reveal><SectionHead kicker={C.features_kicker} title={C.features_title}/><IconRowList items={features} themeColor={themeColor} themeBg10={themeBg10}/></Reveal>}
  {why.length>0&&<Reveal><div className="mb-2"><RedCta/></div><SectionHead kicker={C.why_kicker} title={C.why_title}/><IconRowList items={why} themeColor={themeColor} themeBg10={themeBg10}/></Reveal>}
 {reviews.length>0&&<Reveal><SectionHead kicker={C.reviews_kicker} title={C.reviews_title}/><div className="flex items-center justify-center gap-2 mb-3"><div className="flex items-center gap-0.5 text-amber-500">{Array.from({length:5}).map((_,k)=><Star key={k} className="w-4 h-4" fill="currentColor" strokeWidth={0}/>)}</div><span className="text-[13px] font-semibold text-slate-900">{avgRating}</span><span className="text-[13px] text-slate-500">({reviews.length} রিভিউ)</span></div><div className="grid sm:grid-cols-2 gap-3">{reviews.map((r,i)=><div key={i} className="rounded-xl border border-emerald-100 p-4 bg-white"><div className="flex items-center gap-0.5 text-amber-500 mb-2">{Array.from({length:5}).map((_,k)=><Star key={k} className="w-3.5 h-3.5" fill={k<r.rating?"currentColor":"none"} strokeWidth={1.5}/>)}</div><p className="text-[13.5px] leading-relaxed text-slate-600">{r.text}</p><div className="text-[12px] font-semibold text-slate-900 mt-3">— {r.name}</div></div>)}</div></Reveal>}
   <section id="order" ref={orderSectionRef} className="scroll-mt-4 !mt-5 lp-product-checkout-group"><div className="lp-checkout-shell rounded-2xl bg-white overflow-hidden"><div className="px-3 pt-3 sm:px-4 sm:pt-4 lp-order-note"><ShieldCheck className="w-4 h-4 shrink-0"/><span>নিশ্চিন্তে অর্ডার করুন। অর্ডার করার পরে আমরা আপনাকে কল দিয়ে বিস্তারিত বলে কনফার্ম করবো।</span></div><form id="lp-order-form" onSubmit={submit} className="p-3 sm:p-4 pt-2 sm:pt-2 space-y-3"><div className="border-t border-emerald-100 pt-3"><label className="text-[13px] font-semibold text-slate-900 block mb-1.5">{C.name_label}</label><div className="relative"><User className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="আপনার নাম" className="w-full border border-slate-200 rounded-lg pl-10 pr-3 py-2.5 text-sm bg-slate-50/60 outline-none focus:bg-white focus:border-emerald-500 transition"/></div></div><div><label className="text-[13px] font-semibold text-slate-900 block mb-1.5">{C.phone_label}</label><div className="relative"><Phone className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input ref={phoneRef} required type="tel" inputMode="numeric" maxLength={16} value={form.phone} onChange={e=>{const v=e.target.value.replace(/[^\d]/g,"").slice(0,16);setForm({...form,phone:v});setPhoneErr(p=>p&&isValidBdPhone(v)?"":p)}} aria-invalid={Boolean(phoneErr)} placeholder="01XXXXXXXXX" className={`w-full border rounded-lg pl-10 pr-3 py-2.5 text-sm outline-none transition ${phoneErr ? "border-red-500 bg-red-50/60 focus:border-red-500" : "border-slate-200 bg-slate-50/60 focus:bg-white focus:border-emerald-500"}`} />{phoneErr && <p className="mt-1 text-[12px] font-medium text-red-600">{phoneErr}</p>}</div></div><div><label className="text-[13px] font-semibold text-slate-900 block mb-1.5">{C.address_label}</label><div className="relative"><MapPin className="w-4 h-4 absolute left-3 top-3 text-slate-400"/><textarea required rows={3} value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="গ্রাম/এলাকা, থানা, জেলা" className="w-full border border-slate-200 rounded-lg pl-10 pr-3 py-2.5 text-sm resize-none bg-slate-50/60 outline-none focus:bg-white focus:border-emerald-500 transition"/></div></div>
 <div className="lp-inline-selector"><div className="lp-inline-title">প্যাকেজ সিলেক্ট করুন</div><div className="lp-inline-options">{packages.map((p,i)=>{const active=selectedPkg===i;return <button type="button" key={i} onClick={()=>setSelectedPkg(i)} className="lp-inline-option w-full flex items-center gap-2 border text-left transition bg-white" style={active?{borderColor:themeColor,background:themeBg05,boxShadow:`0 0 0 1px ${themeColor}`}:{borderColor:"#dcece0"}}>{p.image&&<img src={toImg(p.image)} alt="" width={34} height={34} loading="lazy" decoding="async" className="shrink-0 object-cover bg-slate-50"/>}<div className="flex-1 min-w-0"><div className="lp-option-name font-semibold text-slate-900">{p.label}</div>{p.badge&&<span className="inline-block mt-0.5 text-[9px] px-1.5 py-0.5 rounded font-semibold" style={{background:themeBg10,color:themeColor}}>{p.badge}</span>}</div><div className="lp-option-price text-right font-bold text-slate-900 shrink-0">{taka(p.price)}</div><span className="grid place-items-center w-4 h-4 rounded-full border-2 shrink-0" style={active?{background:themeColor,borderColor:themeColor}:{borderColor:"#cbd5e1"}}>{active&&<Check className="w-2.5 h-2.5 text-white" strokeWidth={3}/>}</span></button>})}</div></div>
 <div className="lp-inline-selector"><div className="lp-inline-title">পেমেন্ট মাধ্যম</div><div className="lp-inline-options">{paymentMethods.map(method=>{const active=selectedPayment===method.id;return <button type="button" key={method.id} onClick={()=>setSelectedPayment(method.id)} className="lp-inline-option w-full flex items-center gap-2 border text-left transition bg-white" style={active?{borderColor:themeColor,background:themeBg05,boxShadow:`0 0 0 1px ${themeColor}`}:{borderColor:"#dcece0"}}><span className="grid place-items-center w-8 h-8 rounded-lg shrink-0" style={{background:themeBg10,color:themeColor}}><Wallet className="w-4 h-4"/></span><div className="flex-1 min-w-0"><div className="lp-option-name font-semibold text-slate-900">{method.label}</div><div className="text-[10px] text-slate-500">{method.description}</div></div><span className="grid place-items-center w-4 h-4 rounded-full border-2 shrink-0" style={active?{background:themeColor,borderColor:themeColor}:{borderColor:"#cbd5e1"}}>{active&&<Check className="w-2.5 h-2.5 text-white" strokeWidth={3}/>}</span></button>})}</div></div>
 <div className="lp-inline-summary text-sm divide-y divide-slate-100 overflow-hidden"><div className="flex justify-between px-3.5"><span className="text-slate-500">সাবটোটাল</span><span className="font-semibold text-slate-900">{taka(subtotal)}</span></div><div className="flex justify-between px-3.5"><span className="text-slate-500">ডেলিভারি ফি</span><span className="font-semibold text-slate-900">{deliveryFee===0?"ফ্রি":taka(deliveryFee)}</span></div><div className="flex justify-between px-3.5 bg-emerald-50/60"><span className="font-bold text-slate-900">সর্বমোট</span><span className="font-bold text-[16px]" style={{color:themeColor}}>{taka(total)}</span></div></div>
 <button type="submit" disabled={submitting} style={ctaStyle} className={`w-full text-white py-4 rounded-xl font-extrabold text-[17px] disabled:opacity-60 transition hover:brightness-95 inline-flex items-center justify-center gap-2 shadow-lg ${formInView?"lp-float-up":""}`}><ShieldCheck className="w-[18px] h-[18px]"/>{submitting?"অর্ডার হচ্ছে...":`${C.submit_text} — ${taka(total)}`}</button></form></div></section>
 </div><div className="lp-footer-wrap"><Footer/></div>
 <div className={`fixed bottom-0 left-0 right-0 z-40 transition-all duration-300 ${formInView?"bg-transparent px-3 pt-1 pb-[calc(env(safe-area-inset-bottom,0px)+6px)] pointer-events-none":"bg-white/95 backdrop-blur border-t border-emerald-100 px-3 pt-2 pb-[calc(env(safe-area-inset-bottom,0px)+6px)]"}`}><div className="container mx-auto max-w-2xl">{!formInView?<div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><div className="leading-tight min-w-0"><div className="text-[12px] font-bold text-slate-900 truncate">{selected?.name??brandName}</div><div className="flex items-baseline gap-1.5">{regular&&regular>price&&<span className="text-[12px] line-through text-slate-400">{bnTaka(regular)}</span>}<span className="font-extrabold text-[17px]" style={{color:themeColor}}>{bnTaka(subtotal)}</span></div></div><button onClick={scrollToOrder} style={ctaStyle} className="lp-pulse shrink-0 text-white px-6 py-3 rounded-xl font-extrabold text-[15px] flex items-center justify-center gap-2 transition hover:brightness-95"><ShoppingCart className="w-[18px] h-[18px]"/>{cta}</button></div>:<div className="pointer-events-auto"><button type="submit" form="lp-order-form" disabled={submitting} className="lp-confirm-cta"><ShieldCheck className="w-[18px] h-[18px]"/>{submitting?"অর্ডার হচ্ছে...":<>অর্ডার টি কনফার্ম করুন <span className="lp-confirm-amount">{taka(total)}</span></>}</button></div>}</div></div>
 </div>}
function Reveal({children}:{children:React.ReactNode}){const ref=useRef<HTMLDivElement|null>(null);const[shown,setShown]=useState(false);useEffect(()=>{const el=ref.current;if(!el||typeof IntersectionObserver==="undefined")return setShown(true);const obs=new IntersectionObserver(([e])=>{if(e.isIntersecting){setShown(true);obs.disconnect()}},{rootMargin:"0px 0px -8% 0px"});obs.observe(el);return()=>obs.disconnect()},[]);return <section ref={ref} className={shown?"lp-reveal lp-reveal-in":"lp-reveal"}>{children}</section>}
function Countdown({themeColor,hours=3,title,compact}:{themeColor:string;hours?:number;title?:string;compact?:boolean}){const secs=Math.max(1,Math.round((Number(hours)||3)*3600));const[left,setLeft]=useState(secs);useEffect(()=>{const KEY="lp-offer-deadline";let deadline=Number(localStorage.getItem(KEY)||0);if(!deadline||deadline<Date.now()){deadline=Date.now()+secs*1000;localStorage.setItem(KEY,String(deadline))}const tick=()=>setLeft(Math.max(0,Math.round((deadline-Date.now())/1000)));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[secs]);const pad=(n:number)=>String(n).padStart(2,"0");const parts=[{v:pad(Math.floor(left/3600)),l:"ঘণ্টা"},{v:pad(Math.floor((left%3600)/60)),l:"মিনিট"},{v:pad(left%60),l:"সেকেন্ড"}];if(compact)return <div className="lp-hdr-timer shrink-0"><span className="lp-hdr-timer-note">⏳ অফার শেষ হতে বাকি</span><div className="lp-hdr-timer-row">{parts.map((p,i)=><div key={p.l} className="flex items-center gap-1">{i>0&&<i>:</i>}<div><b>{p.v}</b><em>{p.l}</em></div></div>)}</div></div>;
 return <div className="cute-timer-container"><p className="timer-label">{title||"অফারটি শেষ হতে আর মাত্র..."}</p><div className="timer-display">{parts.map((p,i)=><div key={p.l} className="flex items-start" style={{gap:"8px"}}>{i>0&&<div className="time-separator">:</div>}<div className="time-part"><span>{p.v}</span><label>{p.l}</label></div></div>)}</div></div>}
function LandingVisitTracker({slug}:{slug:string}){useEffect(()=>{trackVisit(`/landing/${slug}`)},[slug]);return null}
function WelcomePopup({themeColor,logo,brand,title,text,cta,mode,image,delay,onCta}:{themeColor:string;logo:string;brand:string;title:string;text:string;cta:string;mode:"text"|"image";image:string;delay:number;onCta?:()=>void}){
 const[open,setOpen]=useState(false);
 const close=useCallback(()=>{setOpen(false);try{sessionStorage.setItem("lp_welcome_seen","1")}catch{}},[]);
 useEffect(()=>{
  try{if(sessionStorage.getItem("lp_welcome_seen")==="1")return}catch{}
  const wait=Math.max(Number(delay)||0,1800);
  const t=setTimeout(()=>setOpen(true),wait);
  return()=>clearTimeout(t);
 },[delay]);
 useEffect(()=>{
  if(!open)return;
  const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")close()};
  window.addEventListener("keydown",onKey);
  return()=>window.removeEventListener("keydown",onKey);
 },[open,close]);
 if(!open)return null;
  const imageMode=mode==="image"&&!!image;
  const CloseBtn=({dark}:{dark?:boolean})=><button onClick={close} aria-label="বন্ধ করুন" className={`absolute right-2.5 top-2.5 z-20 grid h-12 w-12 place-items-center rounded-full shadow-xl ring-2 transition active:scale-95 ${dark?"bg-rose-500 text-white ring-rose-300 hover:bg-rose-600":"bg-rose-500 text-white ring-rose-300 hover:bg-rose-600"}`}><X className="w-7 h-7" strokeWidth={3}/></button>;
  return <div className="fixed inset-0 z-[60] flex items-center justify-center p-4" role="dialog" aria-modal="true">
   <button aria-label="বন্ধ করুন" onClick={close} className="absolute inset-0 bg-slate-950/40 animate-fade-in"/>
   {imageMode
    ?<div className="relative w-full max-w-sm animate-scale-in"><CloseBtn dark/><img src={toImg(image)} alt={title||brand} className="block max-h-[72vh] w-full rounded-2xl bg-white object-contain shadow-2xl"/></div>
    :<div className="relative w-full max-w-sm rounded-3xl border-2 p-6 pt-8 text-center shadow-2xl animate-scale-in overflow-hidden" style={{borderColor:"#facc15",background:`linear-gradient(160deg, ${themeColor}, color-mix(in oklab, ${themeColor} 55%, #052e16))`}}><Leaf className="absolute -left-4 -top-4 w-24 h-24 text-white/10"/><Sprout className="absolute -right-5 -bottom-6 w-28 h-28 text-white/10"/><CloseBtn/><div className="relative flex flex-col items-center gap-3"><span className="grid place-items-center w-16 h-16 rounded-full bg-white/15 ring-2 ring-white/30"><img src={toImg(logo)} alt={brand} className="w-12 h-12 rounded-full object-cover"/></span><h3 className="text-[22px] font-extrabold text-white tracking-tight">{title}</h3><p className="text-[14px] leading-relaxed text-white/85">{text}</p><button onClick={()=>{onCta?.();close()}} className="mt-1 w-full rounded-full bg-white/15 ring-1 ring-white/30 px-6 py-3 font-extrabold text-white text-[16px] transition hover:bg-white/25">{cta}</button><div className="inline-flex items-center gap-1.5 text-[11px] font-semibold text-yellow-300"><ShieldCheck className="w-3.5 h-3.5"/> ১০০% অরিজিনাল বীজের নিশ্চয়তা</div></div></div>}
  </div>
}
