import React from "react";
import type { LandingContent } from "@/lib/landing-content";
import { toImg } from "@/lib/img";

export function ModernProductLanding({ content }: { content: LandingContent }) {
  return <main className="min-h-screen bg-slate-50 text-slate-900">
    <section className="relative overflow-hidden bg-gradient-to-br from-emerald-950 via-emerald-800 to-teal-700 px-4 py-12 text-white sm:py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-2"><div><span className="inline-flex rounded-full bg-white/15 px-4 py-2 text-sm font-bold backdrop-blur">{content.offer_badge_text}</span><h1 className="mt-5 text-4xl font-black leading-tight sm:text-6xl">{content.hero_title || content.seed_title}</h1><p className="mt-4 max-w-xl text-lg text-white/80">{content.hero_note}</p><div className="mt-7 flex flex-wrap items-center gap-4"><strong className="text-3xl">{content.price_prefix} {content.price}</strong><button className="rounded-2xl bg-white px-7 py-4 font-black text-emerald-800 shadow-xl">{content.red_cta_text}</button></div></div><img src={toImg(content.hero_image || content.hero_image_2)} alt="Product" className="mx-auto max-h-[500px] w-full max-w-lg rounded-3xl object-cover shadow-2xl" /></div></section>
    <section className="mx-auto max-w-6xl px-4 py-12"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{["১০০% অরিজিনাল", "দ্রুত ডেলিভারি", "ক্যাশ অন ডেলিভারি", "কাস্টমার সাপোর্ট"].map(x=><div key={x} className="rounded-2xl bg-white p-6 text-center shadow-sm ring-1 ring-slate-100"><div className="text-lg font-extrabold">{x}</div></div>)}</div></section>
    <section className="mx-auto max-w-6xl px-4 pb-16"><div className="rounded-[2rem] bg-white p-6 shadow-xl ring-1 ring-slate-100 sm:p-10"><h2 className="text-center text-3xl font-black">{content.features_title}</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{["উচ্চ মানের পণ্য", "ব্যবহারে সহজ", "সীমিত সময়ের অফার", "বিশ্বস্ত ডেলিভারি"].map(x=><div key={x} className="rounded-2xl bg-slate-50 p-6"><h3 className="font-extrabold">{x}</h3><p className="mt-2 text-slate-600">আপনার জন্য বাছাই করা মানসম্মত সুবিধা ও নির্ভরযোগ্য সেবা।</p></div>)}</div></div></section>
    <section id="order" className="bg-emerald-50 px-4 py-14"><div className="mx-auto max-w-xl rounded-3xl bg-white p-6 shadow-xl"><h2 className="text-center text-3xl font-black">অর্ডার করুন</h2><p className="mt-2 text-center text-slate-500">{content.cod_note}</p><div className="mt-6 space-y-4"><input className="w-full rounded-xl border p-4" placeholder={content.name_label}/><input className="w-full rounded-xl border p-4" placeholder={content.phone_label}/><textarea className="w-full rounded-xl border p-4" placeholder={content.address_label}/><button className="w-full rounded-xl bg-emerald-700 p-4 font-black text-white">{content.submit_text}</button></div></div></section>
  </main>;
}
