import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { listCourierRescue, updateCourierRescue } from "@/lib/courier-rescue.functions";
import { AlertTriangle, Ban, CheckCircle2, Clock3, ExternalLink, Phone, RefreshCw, Truck, UserRound, MessageCircle } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/courier-notes")({ component: CourierNotes });

type Row = any;

const statusText: Record<string,string> = { pending: "Pending", in_progress: "Working", resolved: "Resolved", cancelled: "Cancelled" };
const statusClass: Record<string,string> = { pending: "bg-amber-50 text-amber-700 border-amber-200", in_progress: "bg-blue-50 text-blue-700 border-blue-200", resolved: "bg-emerald-50 text-emerald-700 border-emerald-200", cancelled: "bg-rose-50 text-rose-700 border-rose-200" };

function CourierNotes(){
  const qc=useQueryClient();
  const listFn=useServerFn(listCourierRescue);
  const updateFn=useServerFn(updateCourierRescue);
  const [tab,setTab]=useState<"problem"|"cancel">("problem");
  const [openId,setOpenId]=useState<string|null>(null);
  const [saving,setSaving]=useState<string|null>(null);
  const [note,setNote]=useState("");
  const {data=[],isFetching}=useQuery({queryKey:["courier-rescue"],queryFn:()=>listFn({}),refetchInterval:30000});
  const rows=(data as Row[]).filter(r=>r.issue_type===tab && !["resolved","cancelled"].includes(r.rescue?.status));
  const allProblem=(data as Row[]).filter(r=>r.issue_type==="problem" && !["resolved","cancelled"].includes(r.rescue?.status));
  const allCancel=(data as Row[]).filter(r=>r.issue_type==="cancel" && !["resolved","cancelled"].includes(r.rescue?.status));
  const save=async(row:Row,status:"in_progress"|"resolved"|"cancelled")=>{setSaving(row.id);try{await updateFn({data:{order_id:row.id,issue_type:row.issue_type,status,employee_note:note}});setNote("");await qc.invalidateQueries({queryKey:["courier-rescue"]});toast.success(status==="resolved"?"Issue resolved":"Action saved")}catch(e){toast.error(e instanceof Error?e.message:"Action failed")}finally{setSaving(null)}};
  const openRow=(r:Row)=>{setOpenId(openId===r.id?null:r.id);setNote(r.rescue?.employee_note||"")};
  return <AdminLayout><div className="space-y-5">
    <div className="rounded-2xl bg-gradient-to-r from-slate-950 via-slate-900 to-teal-900 text-white p-5 shadow-xl"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-emerald-300 text-xs font-bold uppercase tracking-wider"><Truck className="w-4 h-4"/> Courier Rescue Center</div><h1 className="text-2xl sm:text-3xl font-black mt-1">Courier Notes</h1><p className="text-slate-300 text-sm mt-1">সমস্যা আসার সাথে সাথে Employee action নিয়ে cancellation কমাবে।</p></div><button onClick={()=>qc.invalidateQueries({queryKey:["courier-rescue"]})} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/10 hover:bg-white/15 border border-white/10 px-4 py-2.5 text-sm font-bold"><RefreshCw className={`w-4 h-4 ${isFetching?"animate-spin":""}`}/> Refresh</button></div></div>
    <div className="grid grid-cols-2 gap-3"><button onClick={()=>setTab("problem")} className={`rounded-2xl border p-4 text-left transition-all ${tab==="problem"?"border-amber-300 bg-amber-50 shadow-md":"bg-white hover:bg-slate-50"}`}><div className="flex items-center justify-between"><span className="text-sm font-bold text-slate-700">⚠️ Problem Notes</span><span className="text-xl font-black">{allProblem.length}</span></div><div className="text-xs text-slate-500 mt-1">Delivery problem / failed attempt</div></button><button onClick={()=>setTab("cancel")} className={`rounded-2xl border p-4 text-left transition-all ${tab==="cancel"?"border-rose-300 bg-rose-50 shadow-md":"bg-white hover:bg-slate-50"}`}><div className="flex items-center justify-between"><span className="text-sm font-bold text-slate-700">❌ Cancel Requests</span><span className="text-xl font-black">{allCancel.length}</span></div><div className="text-xs text-slate-500 mt-1">Customer cancellation risk</div></button></div>
    <div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-slate-900">{tab==="problem"?"Problem Notes":"Cancellation Requests"}</h2><p className="text-xs text-slate-500">শুধু unresolved কাজগুলো দেখানো হচ্ছে</p></div><div className="text-xs font-bold text-slate-500 flex items-center gap-1"><Clock3 className="w-4 h-4"/> Auto refresh 30s</div></div>
    {isFetching&&!data.length?<div className="rounded-2xl bg-white border p-10 text-center text-slate-500">Loading courier notes…</div>:!rows.length?<div className="rounded-2xl bg-white border p-12 text-center"><CheckCircle2 className="w-10 h-10 mx-auto text-emerald-500"/><div className="font-bold mt-2">কোনো pending issue নেই 🎉</div><div className="text-sm text-slate-500 mt-1">সবগুলো আপাতত handled.</div></div>:<div className="space-y-3">{rows.map((r:Row)=><div key={r.id} className="rounded-2xl bg-white border border-slate-200 shadow-sm overflow-hidden"><button onClick={()=>openRow(r)} className="w-full text-left p-4 sm:p-5 hover:bg-slate-50 transition-colors"><div className="flex items-start gap-3"><div className={`shrink-0 h-10 w-10 rounded-xl grid place-items-center ${r.issue_type==="cancel"?"bg-rose-100 text-rose-600":"bg-amber-100 text-amber-600"}`}>{r.issue_type==="cancel"?<Ban className="w-5 h-5"/>:<AlertTriangle className="w-5 h-5"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-black text-slate-900">#{r.invoice_no||r.id.slice(0,8)}</span><span className="text-[11px] rounded-full border px-2 py-0.5 bg-slate-50 text-slate-600">{r.courier_display_name||"Courier"}</span><span className={`text-[11px] rounded-full border px-2 py-0.5 font-bold ${statusClass[r.rescue?.status||"pending"]}`}>{statusText[r.rescue?.status||"pending"]}</span></div><div className="text-sm font-semibold text-slate-700 mt-1 truncate">{r.customer_name||"Customer"} · {r.customer_phone}</div><div className="mt-2 text-sm text-slate-600 bg-slate-50 rounded-xl px-3 py-2">{r.courier_note}</div></div><div className="text-xs text-slate-400">{openId===r.id?"Close":"Open"}</div></div></button>
    {openId===r.id&&<div className="border-t bg-slate-50/70 p-4 sm:p-5 space-y-4"><div className="grid sm:grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-white border p-3"><div className="text-xs text-slate-400">Customer</div><div className="font-bold">{r.customer_name}</div><div className="text-slate-600">{r.customer_phone}</div></div><div className="rounded-xl bg-white border p-3"><div className="text-xs text-slate-400">Address</div><div className="font-medium">{[r.customer_address,r.thana,r.district].filter(Boolean).join(", ")||"—"}</div></div></div><div className="flex flex-wrap gap-2"><a href={`tel:${r.customer_phone}`} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 text-white px-4 py-2.5 text-sm font-bold"><Phone className="w-4 h-4"/> Call</a><a target="_blank" rel="noreferrer" href={`https://wa.me/${String(r.customer_phone||"").replace(/\D/g,"")}`} className="inline-flex items-center gap-2 rounded-xl bg-green-500 text-white px-4 py-2.5 text-sm font-bold"><MessageCircle className="w-4 h-4"/> WhatsApp</a><Link to="/admin/orders" className="inline-flex items-center gap-2 rounded-xl bg-white border px-4 py-2.5 text-sm font-bold text-slate-700"><ExternalLink className="w-4 h-4"/> Open Orders</Link></div><div><label className="text-xs font-bold text-slate-600">Employee Note</label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Customer-এর সাথে কথা বলার ফলাফল লিখুন…" className="mt-1 w-full min-h-20 rounded-xl border bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-emerald-200"/></div><div className="flex flex-wrap gap-2"><button disabled={saving===r.id} onClick={()=>save(r,"in_progress")} className="rounded-xl bg-blue-600 text-white px-4 py-2.5 text-sm font-bold disabled:opacity-50"><UserRound className="inline w-4 h-4 mr-1"/> Working</button><button disabled={saving===r.id} onClick={()=>save(r,"resolved")} className="rounded-xl bg-emerald-600 text-white px-4 py-2.5 text-sm font-bold disabled:opacity-50"><CheckCircle2 className="inline w-4 h-4 mr-1"/> Resolved</button>{r.issue_type==="cancel"&&<button disabled={saving===r.id} onClick={()=>save(r,"cancelled")} className="rounded-xl bg-rose-600 text-white px-4 py-2.5 text-sm font-bold disabled:opacity-50"><Ban className="inline w-4 h-4 mr-1"/> Confirm Cancel</button>}</div><div className="text-[11px] text-slate-500">Courier: {r.courier_display_name||"—"} · Consignment: {r.courier_consignment||"—"}</div></div>}</div>)}</div>}
  </div></AdminLayout>;
}
