import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { UsersRound, MessageSquareText, ChevronRight, ShieldCheck, Star, HelpCircle, MessagesSquare } from "lucide-react";
import { AdminLayout } from "@/components/admin/AdminLayout";

export const Route = createFileRoute("/admin/customers")({ component: CustomerHub });

function CustomerHub(){
 const navigate=useNavigate();
 const cards=[
  {title:"কাস্টমার কন্ট্রোল",subtitle:"কাস্টমার প্রোফাইল, অর্ডার ও ব্লক/আনব্লক সম্পূর্ণভাবে পরিচালনা করুন",icon:UsersRound,tone:"from-sky-500/15 via-cyan-500/10 to-blue-500/5",iconTone:"bg-sky-50 text-sky-700",to:"/admin/customer-management"},
  {title:"রিভিউ + জিজ্ঞেস",subtitle:"প্রোডাক্ট রিভিউ, কাস্টমার প্রশ্ন এবং পোস্ট কমেন্ট এক জায়গা থেকে নিয়ন্ত্রণ করুন",icon:MessageSquareText,tone:"from-emerald-500/15 via-teal-500/10 to-green-500/5",iconTone:"bg-emerald-50 text-emerald-700",to:"/admin/customer-feedback"},
 ];
 return <AdminLayout><div className="mx-auto max-w-5xl animate-in fade-in duration-300"><div className="mb-7 flex items-end gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><UsersRound className="h-6 w-6"/></div><div><div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Customer Center</div><h1 className="text-2xl font-black tracking-tight text-slate-900">কাস্টমার</h1><p className="mt-1 text-sm text-slate-500">কাস্টমার কন্ট্রোল ও কাস্টমার ফিডব্যাক এক জায়গা থেকে পরিচালনা করুন।</p></div></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{cards.map((c,i)=>{const Icon=c.icon;return <button key={c.to} type="button" onClick={()=>navigate({to:c.to as any})} style={{animationDelay:`${i*70}ms`}} className={`group relative overflow-hidden rounded-[24px] border border-slate-200 bg-gradient-to-br ${c.tone} p-6 text-left shadow-sm animate-in fade-in slide-in-from-bottom-3 duration-500 transition-all hover:-translate-y-1.5 hover:border-emerald-300 hover:shadow-2xl focus:outline-none focus:ring-4 focus:ring-emerald-100`}><div className="absolute -right-12 -top-12 h-36 w-36 rounded-full bg-white/30 blur-2xl transition-transform duration-500 group-hover:scale-125"/><div className="relative flex items-start justify-between"><div className={`rounded-2xl p-4 shadow-sm ${c.iconTone}`}><Icon className="h-7 w-7"/></div><span className="rounded-xl bg-white/75 p-2.5 text-slate-400 shadow-sm transition-all group-hover:translate-x-1 group-hover:text-emerald-700"><ChevronRight className="h-5 w-5"/></span></div><h2 className="relative mt-7 text-xl font-black text-slate-900">{c.title}</h2><p className="relative mt-2 max-w-md text-sm leading-6 text-slate-600">{c.subtitle}</p><div className="relative mt-6 inline-flex items-center gap-2 rounded-xl bg-white/80 px-3.5 py-2 text-xs font-black text-slate-700 shadow-sm">বিস্তারিত খুলুন <ChevronRight className="h-3.5 w-3.5"/></div></button>})}</div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-[11px] font-bold text-slate-500"><div className="rounded-2xl border bg-white/70 p-3"><ShieldCheck className="mx-auto mb-1 h-4 w-4 text-sky-600"/>Access Control</div><div className="rounded-2xl border bg-white/70 p-3"><Star className="mx-auto mb-1 h-4 w-4 text-amber-500"/>Real Reviews</div><div className="rounded-2xl border bg-white/70 p-3"><MessagesSquare className="mx-auto mb-1 h-4 w-4 text-emerald-600"/>Questions & Comments</div></div></div></AdminLayout>;
}
