import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, AlertTriangle, CheckCircle2, ChevronDown, Clock3, Package, RefreshCw, ShoppingCart, TrendingUp, Wifi, XCircle } from "lucide-react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { taka, bnDigits } from "@/lib/format";
import { supabase } from "@/lib/personal-supabase/client";
import { getPremiumDashboardReport } from "@/lib/dashboard.functions";
import { DashboardTimeFilter, getDashboardPresetRange, type DashboardPreset, type DashboardRange } from "@/components/admin/DashboardTimeFilter";
import { MetaAdsResultCard } from "@/components/admin/MetaAdsResultCard";

function Card({title,value,hint,icon:Icon,tone}:{title:string;value:string;hint:string;icon:any;tone:string}){return <div className={`group flex h-full min-h-[176px] min-w-0 flex-col rounded-2xl border bg-white p-4 shadow-sm transition-all duration-300 ease-out hover:-translate-y-1 hover:scale-[1.01] hover:shadow-2xl ${tone}`}><div className="flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-50 transition-transform duration-500 group-hover:scale-110 group-hover:rotate-3"><Icon className="h-5 w-5"/></div><Activity className="h-4 w-4 opacity-30 transition-all duration-500 group-hover:scale-125 group-hover:opacity-60"/></div><div className="mt-3 text-[11px] text-slate-500">{title}</div><div className="mt-1 text-2xl font-black text-slate-900 transition-transform duration-300 group-hover:translate-x-0.5">{value}</div><div className="mt-auto pt-1 text-[10px] text-slate-400">{hint}</div></div>}
function Section({title,children,right}:{title:string;children:any;right?:any}){return <section className="mb-4 overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3.5"><h2 className="text-sm font-black text-slate-900">{title}</h2>{right}</div>{children}</section>}

function PipelineCard({data,title="Web Orders",accent="indigo"}:{data:any;title?:string;accent?:"indigo"|"violet"}){
 const [open,setOpen]=useState(false);
 const total=Number(data?.total??0),confirmed=Number(data?.confirmed??0),processing=Number(data?.processing??0),cancelled=Number(data?.cancelled??0),active=Number(data?.active??0);
 const indigo=accent==="indigo";
 const stats=[
  {label:"Confirmed",value:confirmed,icon:CheckCircle2,tone:"text-emerald-600 bg-emerald-50 border-emerald-100"},
  {label:"Processing",value:processing,icon:Clock3,tone:"text-amber-600 bg-amber-50 border-amber-100"},
  {label:"Cancelled",value:cancelled,icon:XCircle,tone:"text-rose-600 bg-rose-50 border-rose-100"},
 ];
 return <div className="min-w-0"><div onClick={()=>setOpen(v=>!v)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")setOpen(v=>!v)}} className={`group flex h-full min-h-[176px] min-w-0 cursor-pointer flex-col overflow-hidden rounded-2xl border bg-white p-4 shadow-sm transition-all duration-300 ease-out hover:-translate-y-1 hover:scale-[1.01] hover:shadow-2xl ${open?(indigo?"border-indigo-300 ring-2 ring-indigo-100":"border-violet-300 ring-2 ring-violet-100"):(indigo?"border-indigo-200":"border-violet-200")}`}>
  <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className={`flex h-11 w-11 items-center justify-center rounded-xl transition-transform duration-500 ${open?(indigo?"scale-110 rotate-3 bg-indigo-100":"scale-110 rotate-3 bg-violet-100"):(indigo?"bg-slate-50":"bg-violet-50")}`}><ShoppingCart className={`h-5 w-5 ${indigo?"text-indigo-600":"text-violet-600"}`}/></div><div><div className="text-[11px] font-bold text-slate-500">{title}</div><div className="mt-0.5 text-2xl font-black text-slate-900">{bnDigits(total)}</div><div className="text-[10px] text-slate-400">{title === "Incomplete Orders" ? "All incomplete-source orders · selected time range" : "Real web orders · selected time range"}</div>{title === "Incomplete Orders" && active > 0 && <div className="mt-1 text-[9px] font-bold text-violet-600">বর্তমানে active incomplete: {bnDigits(active)}</div>}</div></div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] font-black transition-all duration-300 ${open?(indigo?"bg-indigo-600":"bg-violet-600")+" text-white":(indigo?"bg-indigo-50 text-indigo-600":"bg-violet-50 text-violet-600")}`}>{open?"CLOSE":"TAP TO VIEW"}</span><ChevronDown className={`h-5 w-5 text-slate-400 transition-transform duration-500 ${open?"rotate-180":""}`}/></div></div>
  <div className={`grid transition-all duration-500 ease-out ${open?"mt-4 max-h-40 translate-y-0 opacity-100":"mt-0 max-h-0 translate-y-2 overflow-hidden opacity-0"}`}><div className="grid grid-cols-3 gap-2 border-t border-slate-100 pt-3">{stats.map(s=>{const Icon=s.icon;return <div key={s.label} className={`rounded-xl border p-3 text-center transition duration-300 hover:-translate-y-0.5 ${s.tone}`}><Icon className="mx-auto h-4 w-4"/><div className="mt-1 text-xl font-black">{bnDigits(s.value)}</div><div className="text-[9px] font-bold opacity-70">{s.label}</div></div>})}</div></div>
  <div className={`mt-2 flex items-center justify-center gap-1 text-[9px] font-semibold text-slate-400 transition-opacity duration-300 ${open?"opacity-0":"opacity-100"}`}>Confirmed + Processing + Cancelled <ChevronDown className="h-3 w-3"/></div>
 </div></div>
}

function LiveVisitorsCard({live,today}:{live:number;today:number}){return <div className="group flex h-full min-h-[176px] min-w-0 flex-col rounded-2xl border border-emerald-200 bg-white p-4 shadow-sm transition-all duration-300 ease-out hover:-translate-y-1 hover:scale-[1.01] hover:shadow-2xl"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="relative flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50"><span className="absolute h-7 w-7 animate-ping rounded-full bg-emerald-400/30"/><Wifi className="relative h-5 w-5 text-emerald-600"/></div><div><div className="flex items-center gap-2 text-[11px] font-bold text-slate-500">Live Visitors <span className="flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-0.5 text-[8px] font-black text-emerald-600"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-500"/>LIVE</span></div><div className="mt-0.5 text-2xl font-black text-slate-900">{bnDigits(live)}</div><div className="text-[10px] text-slate-400">Currently online · last 2 minutes</div></div></div><div className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-2 text-right"><div className="text-[9px] font-bold text-slate-400">TODAY TOTAL</div><div className="mt-0.5 text-xl font-black text-slate-900">{bnDigits(today)}</div><div className="text-[8px] text-slate-400">Today visitors</div></div></div></div>}

export function PremiumDashboard(){
 const fetchReport=useServerFn(getPremiumDashboardReport); const qc=useQueryClient();
 const [preset,setPreset]=useState<DashboardPreset>("today");
 const [range,setRange]=useState<DashboardRange>(()=>getDashboardPresetRange("today")!);
 const [refreshing,setRefreshing]=useState(false);
 const {data,isFetching,refetch}=useQuery({queryKey:["business-dashboard",range.from,range.to],queryFn:()=>fetchReport({data:range}),staleTime:15000});
 useEffect(()=>{const refresh=()=>qc.invalidateQueries({queryKey:["business-dashboard"]});const ch=supabase.channel("dashboard-live").on("postgres_changes",{event:"*",schema:"public",table:"orders"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"products"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"site_visitors"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"incomplete_orders"},refresh).subscribe();const t=window.setInterval(refresh,30000);return()=>{supabase.removeChannel(ch);window.clearInterval(t)}},[qc]);
 const r:any=data??{real:{revenue:0},webOrders:{total:0,confirmed:0,processing:0,cancelled:0},incompleteOrders:{total:0,confirmed:0,processing:0,cancelled:0,active:0},daily:[],hourly:[],bestSelling:[],lowStock:[],stockSummary:{out:0,low:0,total:0},liveVisitors:0,todayVisitors:0,liveLandingPages:[],employeePerformance:[]};
 const refresh=async()=>{setRefreshing(true);await refetch();setRefreshing(false)};
 const onFilterChange=(next:DashboardPreset,nextRange:DashboardRange|null)=>{if(!nextRange)return;setPreset(next);setRange(nextRange)};
 return <AdminLayout><div className="min-h-full bg-[#f7f9fc] px-1 pb-8"><div className="sticky top-0 z-20 mb-4 flex flex-wrap items-center justify-between gap-2 border-b bg-[#f7f9fc]/95 py-2 backdrop-blur"><div><div className="text-base font-black text-slate-900">Business Command Center</div><div className="text-[10px] text-slate-400">Live database analytics · Dhaka Time</div></div><div className="flex items-center gap-2"><DashboardTimeFilter value={preset} onChange={onFilterChange}/><button onClick={refresh} className="rounded-lg border bg-white p-2 text-slate-500" aria-label="Refresh dashboard"><RefreshCw className={`h-4 w-4 ${refreshing||isFetching?"animate-spin":""}`}/></button></div></div>
 <div className="mb-4 grid grid-cols-2 gap-3 xl:grid-cols-6"><LiveVisitorsCard live={r.liveVisitors} today={r.todayVisitors}/><PipelineCard data={r.webOrders} title="Web Orders" accent="indigo"/><PipelineCard data={r.incompleteOrders} title="Incomplete Orders" accent="violet"/><Card title="Confirmed Sales" value={taka(r.real.revenue)} hint="Real orders only · selected range" icon={TrendingUp} tone="border-rose-200"/><Card title="Stock Alerts" value={bnDigits(r.stockSummary.out+r.stockSummary.low)} hint={`${bnDigits(r.stockSummary.out)} out · ${bnDigits(r.stockSummary.low)} low · current`} icon={AlertTriangle} tone="border-orange-200"/><MetaAdsResultCard range={range}/></div>
 <div className="grid gap-4 xl:grid-cols-[1.65fr_1fr]">
 <Section title="Live Website" right={<span className="flex items-center gap-1 text-[10px] font-bold text-emerald-600"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/> LIVE</span>}><div className="p-4"><div className="mb-3 rounded-xl bg-slate-50 p-3 text-center"><div className="text-3xl font-black text-slate-900">{bnDigits(r.liveVisitors)}</div><div className="text-[10px] text-slate-400">visitors online</div></div><div className="space-y-2">{r.liveLandingPages.slice(0,5).map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-lg border px-3 py-2"><span className="truncate text-xs font-bold text-slate-600">{x.title}</span><b className="text-sm text-emerald-600">{bnDigits(x.visitors)}</b></div>)}{!r.liveLandingPages.length&&<div className="py-4 text-center text-xs text-slate-400">এখন কোনো landing page visitor নেই</div>}</div></div></Section></div>
 <div className="grid gap-4 xl:grid-cols-2"><Section title="Top Selling Products · Real Orders"><div className="divide-y">{r.bestSelling.slice(0,8).map((x:any,i:number)=><div key={x.name} className="flex items-center gap-3 px-4 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-xs font-black text-indigo-600">{i+1}</span><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold text-slate-800">{x.name}</div><div className="text-[10px] text-slate-400">{x.landingPages?.length?`Landing: ${x.landingPages.map((p:any)=>p.title).join(", ")}`:"No linked landing page"}</div></div><div className="text-right"><div className="text-sm font-black text-slate-900">{bnDigits(x.units)} sold</div><div className="text-[10px] text-slate-400">{taka(x.revenue)}</div></div></div>)}{!r.bestSelling.length&&<div className="p-6 text-center text-xs text-slate-400">এই সময়ে real confirmed sale নেই</div>}</div></Section>
 <Section title="Employee Confirmation Performance · All Sources"><div className="divide-y">{r.employeePerformance.slice(0,10).map((x:any,i:number)=><div key={x.user_id||x.name} className="flex items-center gap-3 px-4 py-3"><span className="text-xs font-black text-slate-400">#{i+1}</span><div className="flex-1"><div className="text-xs font-bold text-slate-800">{x.name}</div><div className="text-[10px] text-slate-400">Real + Incomplete source confirmations/cancellations</div></div><div className="text-right"><div className="text-lg font-black text-emerald-600">{bnDigits(x.confirmed)}</div><div className="text-[9px] text-slate-400">cancel {bnDigits(x.cancelled)}</div></div></div>)}{!r.employeePerformance.length&&<div className="p-6 text-center text-xs text-slate-400">Employee data নেই</div>}</div></Section></div>
 <div className="grid gap-4 xl:grid-cols-[1.3fr_1fr]"><Section title="Stock Control"><div className="grid grid-cols-3 gap-2 p-4"><div className="rounded-xl bg-slate-50 p-3 text-center"><Package className="mx-auto h-5 w-5 text-slate-400"/><div className="mt-1 text-xl font-black">{bnDigits(r.stockSummary.total)}</div><div className="text-[9px] text-slate-400">Products · current</div></div><div className="rounded-xl bg-orange-50 p-3 text-center"><AlertTriangle className="mx-auto h-5 w-5 text-orange-500"/><div className="mt-1 text-xl font-black text-orange-600">{bnDigits(r.stockSummary.low)}</div><div className="text-[9px] text-orange-400">Low Stock · current</div></div><div className="rounded-xl bg-rose-50 p-3 text-center"><AlertTriangle className="mx-auto h-5 w-5 text-rose-500"/><div className="mt-1 text-xl font-black text-rose-600">{bnDigits(r.stockSummary.out)}</div><div className="text-[9px] text-rose-400">Out of Stock · current</div></div></div><div className="divide-y">{r.lowStock.slice(0,8).map((x:any)=><div key={x.id} className="flex justify-between px-4 py-2.5 text-xs"><span className="font-semibold text-slate-600">{x.name}</span><b className={x.stock<=0?"text-rose-600":"text-orange-600"}>{x.stock<=0?"OUT":bnDigits(x.stock)}</b></div>)}</div></Section>
 <Section title="Hourly Real Web Order Activity"><div className="h-64 p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={r.hourly}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="#eef2f7"/><XAxis dataKey="label" tick={{fontSize:8}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:8}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="orders" name="Orders" fill="#6366f1" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Section></div>
 </div></AdminLayout>;
}
