import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, CheckCircle2,
  ChevronRight, Clock3, Package, RefreshCw, ShoppingBag, Sparkles, TrendingUp,
  Users, XCircle, Zap,
} from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { taka, bnDigits } from "@/lib/format";
import { getPremiumDashboardReport } from "@/lib/dashboard.functions";

const presets = [
  { key: "today", label: "আজ" },
  { key: "7d", label: "৭ দিন" },
  { key: "30d", label: "৩০ দিন" },
  { key: "month", label: "এই মাস" },
] as const;
type Preset = (typeof presets)[number]["key"];

const pct = (value: number, total: number) => (total ? Math.round((value / total) * 100) : 0);

function MetricCard({ icon: Icon, title, value, hint, tone = "indigo", trend }: {
  icon: typeof Activity; title: string; value: string; hint?: string;
  tone?: "indigo" | "emerald" | "rose" | "amber" | "violet" | "cyan";
  trend?: "up" | "down";
}) {
  const tones = {
    indigo: ["from-indigo-500/15", "to-indigo-500/5", "text-indigo-600", "bg-indigo-500/10"],
    emerald: ["from-emerald-500/15", "to-emerald-500/5", "text-emerald-600", "bg-emerald-500/10"],
    rose: ["from-rose-500/15", "to-rose-500/5", "text-rose-600", "bg-rose-500/10"],
    amber: ["from-amber-500/15", "to-amber-500/5", "text-amber-600", "bg-amber-500/10"],
    violet: ["from-violet-500/15", "to-violet-500/5", "text-violet-600", "bg-violet-500/10"],
    cyan: ["from-cyan-500/15", "to-cyan-500/5", "text-cyan-600", "bg-cyan-500/10"],
  }[tone];
  return <div className="group relative overflow-hidden rounded-2xl border border-slate-200/80 bg-white p-4 shadow-[0_8px_30px_rgba(15,23,42,.04)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_16px_40px_rgba(15,23,42,.09)]">
    <div className={`absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${tones[0]} ${tones[1]}`} />
    <div className="flex items-start justify-between gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${tones[2]} ${tones[3]}`}><Icon className="h-5 w-5" /></div>
      {trend && <span className={`flex items-center gap-0.5 rounded-full px-2 py-1 text-[10px] font-bold ${trend === "up" ? "bg-emerald-50 text-emerald-600" : "bg-rose-50 text-rose-600"}`}>{trend === "up" ? <ArrowUpRight className="h-3 w-3" /> : <ArrowDownRight className="h-3 w-3" />}</span>}
    </div>
    <div className="mt-4 text-[11px] font-medium text-slate-500">{title}</div><div className="mt-1 text-2xl font-black tracking-tight text-slate-900">{value}</div>
    {hint && <div className="mt-1 text-[10px] text-slate-400">{hint}</div>}
  </div>;
}

function FunnelRow({ label, value, total, tone }: { label: string; value: number; total: number; tone: string }) {
  const percent = pct(value, total);
  return <div className="space-y-1.5"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-slate-600">{label}</span><span className="font-black text-slate-900">{bnDigits(value)} <span className="font-medium text-slate-400">({bnDigits(percent)}%)</span></span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone} transition-all duration-1000 ease-out`} style={{ width: `${Math.max(percent, value ? 4 : 0)}%` }} /></div></div>;
}

export function PremiumDashboard() {
  const fetchReport = useServerFn(getPremiumDashboardReport);
  const [preset, setPreset] = useState<Preset>("today");
  const [refreshing, setRefreshing] = useState(false);
  const range = useMemo(() => {
    const now = new Date();
    if (preset === "today") { const from = new Date(); from.setHours(0, 0, 0, 0); return { from: from.toISOString(), to: now.toISOString() }; }
    if (preset === "7d") return { from: new Date(Date.now() - 7 * 86400000).toISOString(), to: now.toISOString() };
    if (preset === "30d") return { from: new Date(Date.now() - 30 * 86400000).toISOString(), to: now.toISOString() };
    return { from: new Date(now.getFullYear(), now.getMonth(), 1).toISOString(), to: now.toISOString() };
  }, [preset]);
  const { data, isFetching, refetch } = useQuery({ queryKey: ["premium-dashboard", range.from, range.to], queryFn: () => fetchReport({ data: range }), staleTime: 30_000 });
  const runRefresh = async () => { setRefreshing(true); await refetch(); setRefreshing(false); };
  const report = data ?? { real: { created: 0, approved: 0, cancelled: 0, pending: 0, revenue: 0 }, incomplete: { created: 0, cancelled: 0, converted: 0, currentWebPending: 0, convertedApproved: 0, convertedCancelled: 0 }, daily: [], bestSelling: [], lowStock: [], stockSummary: { total: 0, low: 0, out: 0 }, customers: 0, products: 0 };
  const realApprovalRate = pct(report.real.approved, report.real.created);
  const incompleteConversionRate = pct(report.incomplete.converted, report.incomplete.created);
  const convertedApprovalRate = pct(report.incomplete.convertedApproved, report.incomplete.converted);

  return <AdminLayout><div className="min-h-full bg-[radial-gradient(circle_at_top_right,_rgba(99,102,241,.08),_transparent_35%),radial-gradient(circle_at_top_left,_rgba(14,165,233,.06),_transparent_30%)]">
    <div className="mb-5 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-white/80 px-3 py-1 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-600 shadow-sm"><Sparkles className="h-3.5 w-3.5" /> Command Center</div><h1 className="text-3xl font-black tracking-tight text-slate-950">ড্যাশবোর্ড</h1><p className="mt-1 text-xs text-slate-500">রিয়েল অর্ডার, ইনকমপ্লিট কনভার্সন, সেলস ও স্টক — এক স্ক্রিনে।</p></div>
      <div className="flex flex-wrap items-center gap-2"><div className="flex rounded-xl border border-slate-200 bg-white p-1 shadow-sm">{presets.map(item => <button key={item.key} onClick={() => setPreset(item.key)} className={`rounded-lg px-3 py-2 text-[11px] font-bold transition-all ${preset === item.key ? "bg-slate-950 text-white shadow-md" : "text-slate-500 hover:bg-slate-50"}`}>{item.label}</button>)}</div><button onClick={runRefresh} disabled={refreshing || isFetching} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold text-slate-700 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${refreshing || isFetching ? "animate-spin" : ""}`} /> আপডেট</button></div>
    </div>

    <div className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-6"><MetricCard icon={ShoppingBag} title="রিয়েল/Web অর্ডার" value={bnDigits(report.real.created)} hint={`${bnDigits(report.real.approved)} approve · ${bnDigits(report.real.cancelled)} cancel`} tone="indigo" /><MetricCard icon={CheckCircle2} title="রিয়েল approve" value={bnDigits(report.real.approved)} hint={`${bnDigits(realApprovalRate)}% approval rate`} tone="emerald" trend="up" /><MetricCard icon={XCircle} title="রিয়েল cancel" value={bnDigits(report.real.cancelled)} hint="এই সময়সীমায়" tone="rose" trend="down" /><MetricCard icon={Zap} title="Incomplete created" value={bnDigits(report.incomplete.created)} hint={`${bnDigits(report.incomplete.converted)} web pending-এ গেছে`} tone="amber" /><MetricCard icon={Clock3} title="Web Pending" value={bnDigits(report.incomplete.currentWebPending)} hint="Incomplete থেকে বর্তমানে pending" tone="violet" /><MetricCard icon={TrendingUp} title="Revenue" value={taka(report.real.revenue)} hint={`${bnDigits(report.products)} products · ${bnDigits(report.customers)} customers`} tone="cyan" /></div>

    <div className="mb-5 grid gap-4 xl:grid-cols-2">
      <section className="relative overflow-hidden rounded-3xl border border-indigo-100 bg-gradient-to-br from-white via-white to-indigo-50/70 p-5 shadow-[0_18px_50px_rgba(79,70,229,.08)]"><div className="absolute -right-16 -top-16 h-40 w-40 rounded-full bg-indigo-400/10 blur-2xl" /><div className="relative flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-black text-slate-900"><ShoppingBag className="h-4 w-4 text-indigo-600" /> রিয়েল / Web Order</div><p className="mt-1 text-[11px] text-slate-500">সরাসরি আসা অর্ডারের পারফরম্যান্স</p></div><div className="rounded-2xl bg-indigo-600 px-3 py-2 text-right text-white shadow-lg shadow-indigo-600/20"><div className="text-[9px] opacity-70">APPROVAL</div><div className="text-lg font-black">{bnDigits(realApprovalRate)}%</div></div></div>
        <div className="relative mt-6 grid grid-cols-3 gap-3">{[{l:"Created",v:report.real.created,c:"bg-indigo-500"},{l:"Approved",v:report.real.approved,c:"bg-emerald-500"},{l:"Cancelled",v:report.real.cancelled,c:"bg-rose-500"}].map(x=><div key={x.l} className="rounded-2xl border border-slate-100 bg-white/90 p-3 shadow-sm"><div className={`mb-2 h-1.5 w-10 rounded-full ${x.c}`} /><div className="text-xl font-black text-slate-900">{bnDigits(x.v)}</div><div className="mt-0.5 text-[10px] font-semibold text-slate-400">{x.l}</div></div>)}</div><div className="relative mt-5"><FunnelRow label="Created → Approved" value={report.real.approved} total={report.real.created} tone="bg-emerald-500" /><div className="mt-4 flex items-center justify-between rounded-2xl bg-indigo-50 px-4 py-3 text-xs"><span className="font-semibold text-indigo-700">Pending এখন</span><span className="font-black text-indigo-950">{bnDigits(report.real.pending)}</span></div></div>
      </section>

      <section className="relative overflow-hidden rounded-3xl border border-amber-100 bg-gradient-to-br from-white via-white to-amber-50/70 p-5 shadow-[0_18px_50px_rgba(245,158,11,.08)]"><div className="absolute -right-16 -top-16 h-40 w-40 rounded-full bg-amber-400/10 blur-2xl" /><div className="relative flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-black text-slate-900"><Activity className="h-4 w-4 text-amber-600" /> Incomplete → Web Pending</div><p className="mt-1 text-[11px] text-slate-500">Incomplete order থেকে তৈরি হওয়া web order-এর journey</p></div><div className="rounded-2xl bg-amber-500 px-3 py-2 text-right text-white shadow-lg shadow-amber-500/20"><div className="text-[9px] opacity-70">CONVERSION</div><div className="text-lg font-black">{bnDigits(incompleteConversionRate)}%</div></div></div>
        <div className="relative mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{[{l:"Created",v:report.incomplete.created},{l:"Web Pending-এ",v:report.incomplete.converted},{l:"Approved",v:report.incomplete.convertedApproved},{l:"Cancelled",v:report.incomplete.convertedCancelled}].map((x,i)=><div key={x.l} className="rounded-2xl border border-slate-100 bg-white/90 p-3 shadow-sm"><div className={`mb-2 h-1.5 w-10 rounded-full ${["bg-amber-500","bg-violet-500","bg-emerald-500","bg-rose-500"][i]}`} /><div className="text-xl font-black text-slate-900">{bnDigits(x.v)}</div><div className="mt-0.5 text-[10px] font-semibold text-slate-400">{x.l}</div></div>)}</div><div className="relative mt-5 space-y-4"><FunnelRow label="Incomplete → Web Pending" value={report.incomplete.converted} total={report.incomplete.created} tone="bg-violet-500" /><FunnelRow label="Web Pending → Approved" value={report.incomplete.convertedApproved} total={report.incomplete.converted} tone="bg-emerald-500" /></div>
      </section>
    </div>

    <div className="mb-5 grid gap-4 xl:grid-cols-[1.7fr_1fr]"><section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_12px_40px_rgba(15,23,42,.05)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-black text-slate-900"><BarChart3 className="h-4 w-4 text-indigo-600" /> Order Pulse</h2><p className="mt-1 text-[10px] text-slate-400">Created বনাম approved বনাম cancelled</p></div><div className="flex gap-3 text-[10px] font-bold text-slate-500"><span>● Created</span><span className="text-emerald-600">● Approved</span><span className="text-rose-500">● Cancel</span></div></div><div className="h-[285px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={report.daily} margin={{top:8,right:4,left:-22,bottom:0}}><defs><linearGradient id="createdFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6366f1" stopOpacity={0.22}/><stop offset="100%" stopColor="#6366f1" stopOpacity={0}/></linearGradient><linearGradient id="approvedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#10b981" stopOpacity={0.18}/><stop offset="100%" stopColor="#10b981" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4" stroke="#eef2f7"/><XAxis dataKey="day" tick={{fontSize:10,fill:"#94a3b8"}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:10,fill:"#94a3b8"}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:16,border:"1px solid #e2e8f0",boxShadow:"0 15px 40px rgba(15,23,42,.12)",fontSize:11}}/><Area type="monotone" dataKey="created" name="Created" stroke="#6366f1" fill="url(#createdFill)" strokeWidth={3}/><Area type="monotone" dataKey="approved" name="Approved" stroke="#10b981" fill="url(#approvedFill)" strokeWidth={3}/><Area type="monotone" dataKey="cancelled" name="Cancelled" stroke="#f43f5e" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section>
      <section className="rounded-3xl border border-slate-200/80 bg-slate-950 p-5 text-white shadow-[0_12px_40px_rgba(15,23,42,.12)]"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-black"><Zap className="h-4 w-4 text-amber-300" /> Live Health</h2><p className="mt-1 text-[10px] text-slate-400">অর্ডার ফানেলের quick signal</p></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[9px] font-bold text-emerald-300">LIVE</span></div><div className="mt-7 flex items-center justify-center"><div className="relative flex h-40 w-40 items-center justify-center rounded-full" style={{background:`conic-gradient(#10b981 ${realApprovalRate}%, #1e293b 0)`}}><div className="flex h-32 w-32 flex-col items-center justify-center rounded-full bg-slate-950"><span className="text-4xl font-black">{bnDigits(realApprovalRate)}%</span><span className="text-[9px] text-slate-500">approval rate</span></div></div></div><div className="mt-7 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white/5 p-3"><div className="text-[9px] text-slate-500">Incomplete conversion</div><div className="mt-1 text-xl font-black text-amber-300">{bnDigits(incompleteConversionRate)}%</div></div><div className="rounded-2xl bg-white/5 p-3"><div className="text-[9px] text-slate-500">Converted approval</div><div className="mt-1 text-xl font-black text-emerald-300">{bnDigits(convertedApprovalRate)}%</div></div></div></section></div>

    <div className="mb-5 grid gap-4 xl:grid-cols-2"><section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_12px_40px_rgba(15,23,42,.05)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-black"><TrendingUp className="h-4 w-4 text-violet-600" /> Best Selling Products</h2><p className="mt-1 text-[10px] text-slate-400">এই সময়সীমায় সবচেয়ে বেশি বিক্রি</p></div><span className="rounded-full bg-violet-50 px-2.5 py-1 text-[9px] font-bold text-violet-600">TOP 5</span></div><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.bestSelling} layout="vertical" margin={{left:10,right:10,top:0,bottom:0}}><CartesianGrid horizontal={false} stroke="#f1f5f9"/><XAxis type="number" allowDecimals={false} hide/><YAxis type="category" dataKey="name" width={120} tick={{fontSize:10,fill:"#64748b"}} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:"#f8fafc"}} contentStyle={{borderRadius:14,border:"1px solid #e2e8f0",fontSize:11}}/><Bar dataKey="units" name="Units" radius={[0,8,8,0]} barSize={18}>{report.bestSelling.map((_,i)=><Cell key={i} fill={["#6366f1","#818cf8","#a78bfa","#c4b5fd","#ddd6fe"][i]}/>)}</Bar></BarChart></ResponsiveContainer></div></section>
      <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_12px_40px_rgba(15,23,42,.05)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-black"><AlertTriangle className="h-4 w-4 text-rose-500" /> Inventory Watch</h2><p className="mt-1 text-[10px] text-slate-400">কম স্টক ও out-of-stock আগে দেখুন</p></div><div className="flex gap-2"><span className="rounded-full bg-rose-50 px-2.5 py-1 text-[9px] font-bold text-rose-600">Out {bnDigits(report.stockSummary.out)}</span><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[9px] font-bold text-amber-600">Low {bnDigits(report.stockSummary.low)}</span></div></div><div className="space-y-2.5">{report.lowStock.length ? report.lowStock.map(p => <div key={p.id} className="group flex items-center gap-3 rounded-2xl border border-slate-100 p-3 transition hover:border-slate-200 hover:bg-slate-50"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${p.stock <= 0 ? "bg-rose-50 text-rose-600" : "bg-amber-50 text-amber-600"}`}><Package className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold text-slate-800">{p.name}</div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${p.stock <= 0 ? "bg-rose-500" : "bg-amber-500"}`} style={{width:`${Math.min(Math.max(p.stock,0),5)/5*100}%`}}/></div></div><div className={`text-sm font-black ${p.stock <= 0 ? "text-rose-600" : "text-amber-600"}`}>{bnDigits(p.stock)}</div></div>) : <div className="flex min-h-44 flex-col items-center justify-center rounded-2xl bg-emerald-50/60 text-center"><CheckCircle2 className="h-8 w-8 text-emerald-500"/><div className="mt-2 text-sm font-black text-emerald-800">স্টক ঠিক আছে</div><div className="mt-1 text-[10px] text-emerald-600">কোনো critical stock নেই</div></div>}</div></section></div>

    <div className="grid gap-4 md:grid-cols-3">{[{icon:Users,label:"মোট কাস্টমার",value:report.customers,sub:"Customer base"},{icon:Package,label:"মোট প্রোডাক্ট",value:report.products,sub:"Active catalog"},{icon:Clock3,label:"Current Web Pending",value:report.incomplete.currentWebPending,sub:"Follow-up needed"}].map(x => <div key={x.label} className="flex items-center gap-4 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100 text-slate-700"><x.icon className="h-5 w-5" /></div><div><div className="text-[10px] font-semibold text-slate-400">{x.label}</div><div className="text-xl font-black text-slate-900">{bnDigits(x.value)}</div><div className="text-[9px] text-slate-400">{x.sub}</div></div><ChevronRight className="ml-auto h-4 w-4 text-slate-300" /></div>)}</div>
  </div></AdminLayout>;
}
