/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomerLoginRouteImport } from './routes/customer-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SocialRouteImport } from './routes/social'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAllApiRouteImport } from './routes/admin/all-api'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCourierRouteImport } from './routes/admin/courier'
import { Route as AdminCustomerFeedbackRouteImport } from './routes/admin/customer-feedback'
import { Route as AdminCustomerManagementRouteImport } from './routes/admin/customer-management'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDeletedOrdersRouteImport } from './routes/admin/deleted-orders'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminFbCallbackRouteImport } from './routes/admin/fb-callback'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminLandingPagesRouteImport } from './routes/admin/landing-pages'
import { Route as AdminLandingSeedsRouteImport } from './routes/admin/landing-seeds'
import { Route as AdminLandingTemplateRouteImport } from './routes/admin/landing-template'
import { Route as AdminMetaAdAccountRouteImport } from './routes/admin/meta-ad-account'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminOrderDivisionRouteImport } from './routes/admin/order-division'
import { Route as AdminOrderImportRouteImport } from './routes/admin/order-import'
import { Route as AdminOrderRateLimitRouteImport } from './routes/admin/order-rate-limit'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as LandingSlugRouteImport } from './routes/landing.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminEmployeesUserIdRouteImport } from './routes/admin/employees_.$userId'
import { Route as ApiPublicFbCapiRouteImport } from './routes/api/public/fb-capi'
import { Route as ApiPublicFbPixelRouteImport } from './routes/api/public/fb-pixel'
import { Route as ApiPublicFbWebhookRouteImport } from './routes/api/public/fb-webhook'
import { Route as ApiPublicIncompleteRouteImport } from './routes/api/public/incomplete'
import { Route as ApiPublicPgRouteImport } from './routes/api/public/pg'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'
import { Route as PresswayyV1InventoryRouteImport } from './routes/presswayy/v1/inventory'
import { Route as PresswayyV1PingRouteImport } from './routes/presswayy/v1/ping'
import { Route as PresswayyV1ResyncRouteImport } from './routes/presswayy/v1/resync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer-login',
  path: '/customer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllApiRoute = AdminAllApiRouteImport.update({
  id: '/admin/all-api',
  path: '/admin/all-api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourierRoute = AdminCourierRouteImport.update({
  id: '/admin/courier',
  path: '/admin/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerFeedbackRoute = AdminCustomerFeedbackRouteImport.update({
  id: '/admin/customer-feedback',
  path: '/admin/customer-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerManagementRoute = AdminCustomerManagementRouteImport.update({
  id: '/admin/customer-management',
  path: '/admin/customer-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeletedOrdersRoute = AdminDeletedOrdersRouteImport.update({
  id: '/admin/deleted-orders',
  path: '/admin/deleted-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFbCallbackRoute = AdminFbCallbackRouteImport.update({
  id: '/admin/fb-callback',
  path: '/admin/fb-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingPagesRoute = AdminLandingPagesRouteImport.update({
  id: '/admin/landing-pages',
  path: '/admin/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingSeedsRoute = AdminLandingSeedsRouteImport.update({
  id: '/admin/landing-seeds',
  path: '/admin/landing-seeds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingTemplateRoute = AdminLandingTemplateRouteImport.update({
  id: '/admin/landing-template',
  path: '/admin/landing-template',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMetaAdAccountRoute = AdminMetaAdAccountRouteImport.update({
  id: '/admin/meta-ad-account',
  path: '/admin/meta-ad-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderDivisionRoute = AdminOrderDivisionRouteImport.update({
  id: '/admin/order-division',
  path: '/admin/order-division',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderImportRoute = AdminOrderImportRouteImport.update({
  id: '/admin/order-import',
  path: '/admin/order-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderRateLimitRoute = AdminOrderRateLimitRouteImport.update({
  id: '/admin/order-rate-limit',
  path: '/admin/order-rate-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSlugRoute = LandingSlugRouteImport.update({
  id: '/landing/$slug',
  path: '/landing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesUserIdRoute = AdminEmployeesUserIdRouteImport.update({
  id: '/admin/employees_/$userId',
  path: '/admin/employees/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbCapiRoute = ApiPublicFbCapiRouteImport.update({
  id: '/api/public/fb-capi',
  path: '/api/public/fb-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbPixelRoute = ApiPublicFbPixelRouteImport.update({
  id: '/api/public/fb-pixel',
  path: '/api/public/fb-pixel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbWebhookRoute = ApiPublicFbWebhookRouteImport.update({
  id: '/api/public/fb-webhook',
  path: '/api/public/fb-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIncompleteRoute = ApiPublicIncompleteRouteImport.update({
  id: '/api/public/incomplete',
  path: '/api/public/incomplete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPgRoute = ApiPublicPgRouteImport.update({
  id: '/api/public/pg',
  path: '/api/public/pg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PresswayyV1InventoryRoute = PresswayyV1InventoryRouteImport.update({
  id: '/presswayy/v1/inventory',
  path: '/presswayy/v1/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PresswayyV1PingRoute = PresswayyV1PingRouteImport.update({
  id: '/presswayy/v1/ping',
  path: '/presswayy/v1/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const PresswayyV1ResyncRoute = PresswayyV1ResyncRouteImport.update({
  id: '/presswayy/v1/resync',
  path: '/presswayy/v1/resync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customer-login': typeof CustomerLoginRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/admin/all-api': typeof AdminAllApiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customer-feedback': typeof AdminCustomerFeedbackRoute
  '/admin/customer-management': typeof AdminCustomerManagementRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deleted-orders': typeof AdminDeletedOrdersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/fb-callback': typeof AdminFbCallbackRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/landing-seeds': typeof AdminLandingSeedsRoute
  '/admin/landing-template': typeof AdminLandingTemplateRoute
  '/admin/meta-ad-account': typeof AdminMetaAdAccountRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/order-division': typeof AdminOrderDivisionRoute
  '/admin/order-import': typeof AdminOrderImportRoute
  '/admin/order-rate-limit': typeof AdminOrderRateLimitRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/employees/$userId': typeof AdminEmployeesUserIdRoute
  '/api/public/fb-capi': typeof ApiPublicFbCapiRoute
  '/api/public/fb-pixel': typeof ApiPublicFbPixelRoute
  '/api/public/fb-webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/incomplete': typeof ApiPublicIncompleteRoute
  '/api/public/pg': typeof ApiPublicPgRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/presswayy/v1/inventory': typeof PresswayyV1InventoryRoute
  '/presswayy/v1/ping': typeof PresswayyV1PingRoute
  '/presswayy/v1/resync': typeof PresswayyV1ResyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customer-login': typeof CustomerLoginRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/admin/all-api': typeof AdminAllApiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customer-feedback': typeof AdminCustomerFeedbackRoute
  '/admin/customer-management': typeof AdminCustomerManagementRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deleted-orders': typeof AdminDeletedOrdersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/fb-callback': typeof AdminFbCallbackRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/landing-seeds': typeof AdminLandingSeedsRoute
  '/admin/landing-template': typeof AdminLandingTemplateRoute
  '/admin/meta-ad-account': typeof AdminMetaAdAccountRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/order-division': typeof AdminOrderDivisionRoute
  '/admin/order-import': typeof AdminOrderImportRoute
  '/admin/order-rate-limit': typeof AdminOrderRateLimitRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/employees/$userId': typeof AdminEmployeesUserIdRoute
  '/api/public/fb-capi': typeof ApiPublicFbCapiRoute
  '/api/public/fb-pixel': typeof ApiPublicFbPixelRoute
  '/api/public/fb-webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/incomplete': typeof ApiPublicIncompleteRoute
  '/api/public/pg': typeof ApiPublicPgRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/presswayy/v1/inventory': typeof PresswayyV1InventoryRoute
  '/presswayy/v1/ping': typeof PresswayyV1PingRoute
  '/presswayy/v1/resync': typeof PresswayyV1ResyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customer-login': typeof CustomerLoginRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/admin/all-api': typeof AdminAllApiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customer-feedback': typeof AdminCustomerFeedbackRoute
  '/admin/customer-management': typeof AdminCustomerManagementRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deleted-orders': typeof AdminDeletedOrdersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/fb-callback': typeof AdminFbCallbackRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/landing-seeds': typeof AdminLandingSeedsRoute
  '/admin/landing-template': typeof AdminLandingTemplateRoute
  '/admin/meta-ad-account': typeof AdminMetaAdAccountRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/order-division': typeof AdminOrderDivisionRoute
  '/admin/order-import': typeof AdminOrderImportRoute
  '/admin/order-rate-limit': typeof AdminOrderRateLimitRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/employees_/$userId': typeof AdminEmployeesUserIdRoute
  '/api/public/fb-capi': typeof ApiPublicFbCapiRoute
  '/api/public/fb-pixel': typeof ApiPublicFbPixelRoute
  '/api/public/fb-webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/incomplete': typeof ApiPublicIncompleteRoute
  '/api/public/pg': typeof ApiPublicPgRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/presswayy/v1/inventory': typeof PresswayyV1InventoryRoute
  '/presswayy/v1/ping': typeof PresswayyV1PingRoute
  '/presswayy/v1/resync': typeof PresswayyV1ResyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/customer-login'
    | '/login'
    | '/media'
    | '/offers'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/admin/all-api'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customer-feedback'
    | '/admin/customer-management'
    | '/admin/customers'
    | '/admin/deleted-orders'
    | '/admin/employees'
    | '/admin/fb-callback'
    | '/admin/integrations'
    | '/admin/landing-pages'
    | '/admin/landing-seeds'
    | '/admin/landing-template'
    | '/admin/meta-ad-account'
    | '/admin/offers'
    | '/admin/order-division'
    | '/admin/order-import'
    | '/admin/order-rate-limit'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/category/$slug'
    | '/landing/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/employees/$userId'
    | '/api/public/fb-capi'
    | '/api/public/fb-pixel'
    | '/api/public/fb-webhook'
    | '/api/public/incomplete'
    | '/api/public/pg'
    | '/api/public/sitemap'
    | '/presswayy/v1/inventory'
    | '/presswayy/v1/ping'
    | '/presswayy/v1/resync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/customer-login'
    | '/login'
    | '/media'
    | '/offers'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/admin/all-api'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customer-feedback'
    | '/admin/customer-management'
    | '/admin/customers'
    | '/admin/deleted-orders'
    | '/admin/employees'
    | '/admin/fb-callback'
    | '/admin/integrations'
    | '/admin/landing-pages'
    | '/admin/landing-seeds'
    | '/admin/landing-template'
    | '/admin/meta-ad-account'
    | '/admin/offers'
    | '/admin/order-division'
    | '/admin/order-import'
    | '/admin/order-rate-limit'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/category/$slug'
    | '/landing/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin'
    | '/admin/employees/$userId'
    | '/api/public/fb-capi'
    | '/api/public/fb-pixel'
    | '/api/public/fb-webhook'
    | '/api/public/incomplete'
    | '/api/public/pg'
    | '/api/public/sitemap'
    | '/presswayy/v1/inventory'
    | '/presswayy/v1/ping'
    | '/presswayy/v1/resync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/customer-login'
    | '/login'
    | '/media'
    | '/offers'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/admin/all-api'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customer-feedback'
    | '/admin/customer-management'
    | '/admin/customers'
    | '/admin/deleted-orders'
    | '/admin/employees'
    | '/admin/fb-callback'
    | '/admin/integrations'
    | '/admin/landing-pages'
    | '/admin/landing-seeds'
    | '/admin/landing-template'
    | '/admin/meta-ad-account'
    | '/admin/offers'
    | '/admin/order-division'
    | '/admin/order-import'
    | '/admin/order-rate-limit'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/category/$slug'
    | '/landing/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/employees_/$userId'
    | '/api/public/fb-capi'
    | '/api/public/fb-pixel'
    | '/api/public/fb-webhook'
    | '/api/public/incomplete'
    | '/api/public/pg'
    | '/api/public/sitemap'
    | '/presswayy/v1/inventory'
    | '/presswayy/v1/ping'
    | '/presswayy/v1/resync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  OffersRoute: typeof OffersRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  AdminAllApiRoute: typeof AdminAllApiRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCourierRoute: typeof AdminCourierRoute
  AdminCustomerFeedbackRoute: typeof AdminCustomerFeedbackRoute
  AdminCustomerManagementRoute: typeof AdminCustomerManagementRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeletedOrdersRoute: typeof AdminDeletedOrdersRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminFbCallbackRoute: typeof AdminFbCallbackRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLandingPagesRoute: typeof AdminLandingPagesRoute
  AdminLandingSeedsRoute: typeof AdminLandingSeedsRoute
  AdminLandingTemplateRoute: typeof AdminLandingTemplateRoute
  AdminMetaAdAccountRoute: typeof AdminMetaAdAccountRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminOrderDivisionRoute: typeof AdminOrderDivisionRoute
  AdminOrderImportRoute: typeof AdminOrderImportRoute
  AdminOrderRateLimitRoute: typeof AdminOrderRateLimitRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LandingSlugRoute: typeof LandingSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmployeesUserIdRoute: typeof AdminEmployeesUserIdRoute
  ApiPublicFbCapiRoute: typeof ApiPublicFbCapiRoute
  ApiPublicFbPixelRoute: typeof ApiPublicFbPixelRoute
  ApiPublicFbWebhookRoute: typeof ApiPublicFbWebhookRoute
  ApiPublicIncompleteRoute: typeof ApiPublicIncompleteRoute
  ApiPublicPgRoute: typeof ApiPublicPgRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
  PresswayyV1InventoryRoute: typeof PresswayyV1InventoryRoute
  PresswayyV1PingRoute: typeof PresswayyV1PingRoute
  PresswayyV1ResyncRoute: typeof PresswayyV1ResyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-login': {
      id: '/customer-login'
      path: '/customer-login'
      fullPath: '/customer-login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/all-api': {
      id: '/admin/all-api'
      path: '/admin/all-api'
      fullPath: '/admin/all-api'
      preLoaderRoute: typeof AdminAllApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courier': {
      id: '/admin/courier'
      path: '/admin/courier'
      fullPath: '/admin/courier'
      preLoaderRoute: typeof AdminCourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-feedback': {
      id: '/admin/customer-feedback'
      path: '/admin/customer-feedback'
      fullPath: '/admin/customer-feedback'
      preLoaderRoute: typeof AdminCustomerFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-management': {
      id: '/admin/customer-management'
      path: '/admin/customer-management'
      fullPath: '/admin/customer-management'
      preLoaderRoute: typeof AdminCustomerManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deleted-orders': {
      id: '/admin/deleted-orders'
      path: '/admin/deleted-orders'
      fullPath: '/admin/deleted-orders'
      preLoaderRoute: typeof AdminDeletedOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fb-callback': {
      id: '/admin/fb-callback'
      path: '/admin/fb-callback'
      fullPath: '/admin/fb-callback'
      preLoaderRoute: typeof AdminFbCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing-pages': {
      id: '/admin/landing-pages'
      path: '/admin/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AdminLandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing-seeds': {
      id: '/admin/landing-seeds'
      path: '/admin/landing-seeds'
      fullPath: '/admin/landing-seeds'
      preLoaderRoute: typeof AdminLandingSeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing-template': {
      id: '/admin/landing-template'
      path: '/admin/landing-template'
      fullPath: '/admin/landing-template'
      preLoaderRoute: typeof AdminLandingTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/meta-ad-account': {
      id: '/admin/meta-ad-account'
      path: '/admin/meta-ad-account'
      fullPath: '/admin/meta-ad-account'
      preLoaderRoute: typeof AdminMetaAdAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/order-division': {
      id: '/admin/order-division'
      path: '/admin/order-division'
      fullPath: '/admin/order-division'
      preLoaderRoute: typeof AdminOrderDivisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/order-import': {
      id: '/admin/order-import'
      path: '/admin/order-import'
      fullPath: '/admin/order-import'
      preLoaderRoute: typeof AdminOrderImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/order-rate-limit': {
      id: '/admin/order-rate-limit'
      path: '/admin/order-rate-limit'
      fullPath: '/admin/order-rate-limit'
      preLoaderRoute: typeof AdminOrderRateLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/$slug': {
      id: '/landing/$slug'
      path: '/landing/$slug'
      fullPath: '/landing/$slug'
      preLoaderRoute: typeof LandingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees_/$userId': {
      id: '/admin/employees_/$userId'
      path: '/admin/employees/$userId'
      fullPath: '/admin/employees/$userId'
      preLoaderRoute: typeof AdminEmployeesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb-capi': {
      id: '/api/public/fb-capi'
      path: '/api/public/fb-capi'
      fullPath: '/api/public/fb-capi'
      preLoaderRoute: typeof ApiPublicFbCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb-pixel': {
      id: '/api/public/fb-pixel'
      path: '/api/public/fb-pixel'
      fullPath: '/api/public/fb-pixel'
      preLoaderRoute: typeof ApiPublicFbPixelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb-webhook': {
      id: '/api/public/fb-webhook'
      path: '/api/public/fb-webhook'
      fullPath: '/api/public/fb-webhook'
      preLoaderRoute: typeof ApiPublicFbWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/incomplete': {
      id: '/api/public/incomplete'
      path: '/api/public/incomplete'
      fullPath: '/api/public/incomplete'
      preLoaderRoute: typeof ApiPublicIncompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pg': {
      id: '/api/public/pg'
      path: '/api/public/pg'
      fullPath: '/api/public/pg'
      preLoaderRoute: typeof ApiPublicPgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presswayy/v1/inventory': {
      id: '/presswayy/v1/inventory'
      path: '/presswayy/v1/inventory'
      fullPath: '/presswayy/v1/inventory'
      preLoaderRoute: typeof PresswayyV1InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presswayy/v1/ping': {
      id: '/presswayy/v1/ping'
      path: '/presswayy/v1/ping'
      fullPath: '/presswayy/v1/ping'
      preLoaderRoute: typeof PresswayyV1PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presswayy/v1/resync': {
      id: '/presswayy/v1/resync'
      path: '/presswayy/v1/resync'
      fullPath: '/presswayy/v1/resync'
      preLoaderRoute: typeof PresswayyV1ResyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  OffersRoute: OffersRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  AdminAllApiRoute: AdminAllApiRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCourierRoute: AdminCourierRoute,
  AdminCustomerFeedbackRoute: AdminCustomerFeedbackRoute,
  AdminCustomerManagementRoute: AdminCustomerManagementRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeletedOrdersRoute: AdminDeletedOrdersRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminFbCallbackRoute: AdminFbCallbackRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLandingPagesRoute: AdminLandingPagesRoute,
  AdminLandingSeedsRoute: AdminLandingSeedsRoute,
  AdminLandingTemplateRoute: AdminLandingTemplateRoute,
  AdminMetaAdAccountRoute: AdminMetaAdAccountRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminOrderDivisionRoute: AdminOrderDivisionRoute,
  AdminOrderImportRoute: AdminOrderImportRoute,
  AdminOrderRateLimitRoute: AdminOrderRateLimitRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CategorySlugRoute: CategorySlugRoute,
  LandingSlugRoute: LandingSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmployeesUserIdRoute: AdminEmployeesUserIdRoute,
  ApiPublicFbCapiRoute: ApiPublicFbCapiRoute,
  ApiPublicFbPixelRoute: ApiPublicFbPixelRoute,
  ApiPublicFbWebhookRoute: ApiPublicFbWebhookRoute,
  ApiPublicIncompleteRoute: ApiPublicIncompleteRoute,
  ApiPublicPgRoute: ApiPublicPgRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
  PresswayyV1InventoryRoute: PresswayyV1InventoryRoute,
  PresswayyV1PingRoute: PresswayyV1PingRoute,
  PresswayyV1ResyncRoute: PresswayyV1ResyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
