/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAllApiRouteImport } from './routes/admin/all-api'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCourierRouteImport } from './routes/admin/courier'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminFbCallbackRouteImport } from './routes/admin/fb-callback'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminLandingPagesRouteImport } from './routes/admin/landing-pages'
import { Route as AdminOrderImportRouteImport } from './routes/admin/order-import'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as LandingSlugRouteImport } from './routes/landing.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminEmployeesUserIdRouteImport } from './routes/admin/employees_.$userId'
import { Route as ApiPublicFbAutopilotRouteImport } from './routes/api/public/fb-autopilot'
import { Route as ApiPublicFbWebhookRouteImport } from './routes/api/public/fb-webhook'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllApiRoute = AdminAllApiRouteImport.update({
  id: '/admin/all-api',
  path: '/admin/all-api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourierRoute = AdminCourierRouteImport.update({
  id: '/admin/courier',
  path: '/admin/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFbCallbackRoute = AdminFbCallbackRouteImport.update({
  id: '/admin/fb-callback',
  path: '/admin/fb-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingPagesRoute = AdminLandingPagesRouteImport.update({
  id: '/admin/landing-pages',
  path: '/admin/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderImportRoute = AdminOrderImportRouteImport.update({
  id: '/admin/order-import',
  path: '/admin/order-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSlugRoute = LandingSlugRouteImport.update({
  id: '/landing/$slug',
  path: '/landing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesUserIdRoute = AdminEmployeesUserIdRouteImport.update({
  id: '/admin/employees_/$userId',
  path: '/admin/employees/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbAutopilotRoute = ApiPublicFbAutopilotRouteImport.update({
  id: '/api/public/fb-autopilot',
  path: '/api/public/fb-autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbWebhookRoute = ApiPublicFbWebhookRouteImport.update({
  id: '/api/public/fb-webhook',
  path: '/api/public/fb-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/all-api': typeof AdminAllApiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/fb-callback': typeof AdminFbCallbackRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/order-import': typeof AdminOrderImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/employees/$userId': typeof AdminEmployeesUserIdRoute
  '/api/public/fb-autopilot': typeof ApiPublicFbAutopilotRoute
  '/api/public/fb-webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/all-api': typeof AdminAllApiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/fb-callback': typeof AdminFbCallbackRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/order-import': typeof AdminOrderImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/employees/$userId': typeof AdminEmployeesUserIdRoute
  '/api/public/fb-autopilot': typeof ApiPublicFbAutopilotRoute
  '/api/public/fb-webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/all-api': typeof AdminAllApiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/fb-callback': typeof AdminFbCallbackRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/order-import': typeof AdminOrderImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/employees_/$userId': typeof AdminEmployeesUserIdRoute
  '/api/public/fb-autopilot': typeof ApiPublicFbAutopilotRoute
  '/api/public/fb-webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/all-api'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/fb-callback'
    | '/admin/integrations'
    | '/admin/landing-pages'
    | '/admin/order-import'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/category/$slug'
    | '/landing/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/employees/$userId'
    | '/api/public/fb-autopilot'
    | '/api/public/fb-webhook'
    | '/api/public/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/all-api'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/fb-callback'
    | '/admin/integrations'
    | '/admin/landing-pages'
    | '/admin/order-import'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/category/$slug'
    | '/landing/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin'
    | '/admin/employees/$userId'
    | '/api/public/fb-autopilot'
    | '/api/public/fb-webhook'
    | '/api/public/sitemap'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/all-api'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/fb-callback'
    | '/admin/integrations'
    | '/admin/landing-pages'
    | '/admin/order-import'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/category/$slug'
    | '/landing/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/employees_/$userId'
    | '/api/public/fb-autopilot'
    | '/api/public/fb-webhook'
    | '/api/public/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAllApiRoute: typeof AdminAllApiRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCourierRoute: typeof AdminCourierRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminFbCallbackRoute: typeof AdminFbCallbackRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLandingPagesRoute: typeof AdminLandingPagesRoute
  AdminOrderImportRoute: typeof AdminOrderImportRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LandingSlugRoute: typeof LandingSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmployeesUserIdRoute: typeof AdminEmployeesUserIdRoute
  ApiPublicFbAutopilotRoute: typeof ApiPublicFbAutopilotRoute
  ApiPublicFbWebhookRoute: typeof ApiPublicFbWebhookRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/all-api': {
      id: '/admin/all-api'
      path: '/admin/all-api'
      fullPath: '/admin/all-api'
      preLoaderRoute: typeof AdminAllApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courier': {
      id: '/admin/courier'
      path: '/admin/courier'
      fullPath: '/admin/courier'
      preLoaderRoute: typeof AdminCourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fb-callback': {
      id: '/admin/fb-callback'
      path: '/admin/fb-callback'
      fullPath: '/admin/fb-callback'
      preLoaderRoute: typeof AdminFbCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing-pages': {
      id: '/admin/landing-pages'
      path: '/admin/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AdminLandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/order-import': {
      id: '/admin/order-import'
      path: '/admin/order-import'
      fullPath: '/admin/order-import'
      preLoaderRoute: typeof AdminOrderImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/$slug': {
      id: '/landing/$slug'
      path: '/landing/$slug'
      fullPath: '/landing/$slug'
      preLoaderRoute: typeof LandingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees_/$userId': {
      id: '/admin/employees_/$userId'
      path: '/admin/employees/$userId'
      fullPath: '/admin/employees/$userId'
      preLoaderRoute: typeof AdminEmployeesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb-autopilot': {
      id: '/api/public/fb-autopilot'
      path: '/api/public/fb-autopilot'
      fullPath: '/api/public/fb-autopilot'
      preLoaderRoute: typeof ApiPublicFbAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb-webhook': {
      id: '/api/public/fb-webhook'
      path: '/api/public/fb-webhook'
      fullPath: '/api/public/fb-webhook'
      preLoaderRoute: typeof ApiPublicFbWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAllApiRoute: AdminAllApiRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCourierRoute: AdminCourierRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminFbCallbackRoute: AdminFbCallbackRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLandingPagesRoute: AdminLandingPagesRoute,
  AdminOrderImportRoute: AdminOrderImportRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CategorySlugRoute: CategorySlugRoute,
  LandingSlugRoute: LandingSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmployeesUserIdRoute: AdminEmployeesUserIdRoute,
  ApiPublicFbAutopilotRoute: ApiPublicFbAutopilotRoute,
  ApiPublicFbWebhookRoute: ApiPublicFbWebhookRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
