-- Durable Meta Purchase outbox: only used when immediate CAPI delivery fails.
create table if not exists public.meta_capi_purchase_outbox (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  payload jsonb not null,
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists meta_capi_purchase_outbox_retry_idx
  on public.meta_capi_purchase_outbox (next_attempt_at)
  where sent_at is null;

revoke all on public.meta_capi_purchase_outbox from public, anon, authenticated;

create or replace function public.queue_meta_capi_purchase(p_event_id text, p_body jsonb)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if nullif(trim(p_event_id), '') is null then return false; end if;
  if p_body->'data'->0->>'event_name' <> 'Purchase' then return false; end if;
  insert into public.meta_capi_purchase_outbox(event_id, payload)
  values (p_event_id, p_body)
  on conflict (event_id) do update
    set payload = excluded.payload,
        next_attempt_at = least(public.meta_capi_purchase_outbox.next_attempt_at, now()),
        sent_at = null;
  return true;
exception when others then
  return false;
end;
$$;

revoke all on function public.queue_meta_capi_purchase(text,jsonb) from public, anon, authenticated;
grant execute on function public.queue_meta_capi_purchase(text,jsonb) to service_role;

create or replace function public.retry_meta_capi_purchase_outbox()
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  r record;
  v_ok boolean;
  v_count integer := 0;
begin
  for r in
    select id, event_id, payload, attempts
    from public.meta_capi_purchase_outbox
    where sent_at is null and next_attempt_at <= now()
    order by next_attempt_at, id
    limit 20
    for update skip locked
  loop
    v_ok := public.dispatch_meta_capi_event(r.payload);
    if v_ok then
      update public.meta_capi_purchase_outbox
        set sent_at = now(), last_error = null
        where id = r.id;
      delete from public.meta_capi_purchase_outbox where id = r.id;
      v_count := v_count + 1;
    else
      update public.meta_capi_purchase_outbox
        set attempts = r.attempts + 1,
            next_attempt_at = now() + make_interval(secs => least(3600, greatest(60, (2 ^ least(r.attempts + 1, 6)) * 60))),
            last_error = 'Meta CAPI dispatch failed'
        where id = r.id;
    end if;
  end loop;
  return v_count;
exception when others then
  raise warning 'Meta Purchase outbox retry failed: %', sqlerrm;
  return v_count;
end;
$$;

revoke all on function public.retry_meta_capi_purchase_outbox() from public, anon, authenticated;
grant execute on function public.retry_meta_capi_purchase_outbox() to service_role;

do $$
begin
  if not exists (select 1 from cron.job where jobname = 'meta_capi_purchase_retry') then
    perform cron.schedule('meta_capi_purchase_retry', '* * * * *', 'select public.retry_meta_capi_purchase_outbox();');
  end if;
end
$$;