-- Fix employee confirmation performance attribution (confirmed_by/confirmed_at aware)
CREATE OR REPLACE FUNCTION public.dashboard_egress_summary(p_from timestamp with time zone, p_to timestamp with time zone)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
with
 o as (select id,source::text as source,status::text as status,total,created_at,created_by,assigned_to,confirmed_at,confirmed_by from public.orders where created_at between p_from and p_to),
 d as (select id,(order_data->>'source')::text as source,original_status::text as status,total,original_created_at as created_at,null::uuid as created_by,null::uuid as assigned_to,nullif(order_data->>'confirmed_at','')::timestamptz as confirmed_at,nullif(order_data->>'confirmed_by','')::uuid as confirmed_by from public.deleted_orders where original_created_at between p_from and p_to),
 a as (select * from o union all select d.* from d where not exists(select 1 from o where o.id=d.id)),
 r as (select * from a where lower(coalesce(a.source::text,''))<>'incomplete'),
 w as (select * from r where lower(coalesce(r.source::text,''))='web'),
 i as (select * from a where lower(coalesce(a.source::text,''))='incomplete'),
 c as (select * from r where lower(coalesce(r.status::text,'')) in ('pending','rts','shipped','delivered','pending_return','returned','partial')),
 p as (select * from w where lower(coalesce(w.status::text,'')) in ('web_pending','processing')),
 x as (select * from w where lower(coalesce(w.status::text,'')) in ('cancelled','canceled')),
 ic as (select coalesce(sum(oi.quantity*coalesce(pr.cost,0)),0) v from public.order_items oi join c on c.id=oi.order_id left join public.products pr on pr.id=oi.product_id),
 b as (select oi.product_id,max(oi.product_name) product_name,sum(oi.quantity) units,sum(oi.subtotal) revenue from public.order_items oi join c on c.id=oi.order_id group by oi.product_id order by units desc limit 10),
 s as (select coalesce(a.source::text,'unknown') source,count(*) count,coalesce(sum(total),0) revenue from a group by 1 order by count desc),
 dy as (select to_char(created_at at time zone 'Asia/Dhaka','YYYY-MM-DD') day_key,count(*) filter(where lower(coalesce(a.source::text,''))='web') created,count(*) filter(where lower(coalesce(a.source::text,''))='web' and lower(coalesce(a.status::text,'')) in ('web_pending','processing')) processing,count(*) filter(where lower(coalesce(a.source::text,''))='web' and lower(coalesce(a.status::text,'')) in ('pending','rts','shipped','delivered','pending_return','returned','partial')) confirmed,count(*) filter(where lower(coalesce(a.source::text,''))='web' and lower(coalesce(a.status::text,'')) in ('cancelled','canceled')) cancelled from a group by 1 order by 1),
 hr as (select extract(hour from created_at at time zone 'Asia/Dhaka')::int hour_key,count(*) filter(where lower(coalesce(a.source::text,''))='web') orders from a group by 1),
 eps as (select o.created_by,o.confirmed_by,o.confirmed_at,o.created_at,o.status::text st,o.source::text src from public.orders o where o.confirmed_at between p_from and p_to or o.created_at between p_from and p_to),
 epa as (select coalesce(confirmed_by,created_by) actor,coalesce(confirmed_at,created_at) act_at,st,src from eps),
 ep as (select e.user_id,e.name,count(*) filter(where x.act_at between p_from and p_to and lower(coalesce(x.src,''))='web' and lower(coalesce(x.st,'')) in ('pending','rts','shipped','delivered','pending_return','returned','partial')) confirmed,count(*) filter(where x.act_at between p_from and p_to and lower(coalesce(x.src,''))='web' and lower(coalesce(x.st,'')) in ('cancelled','canceled')) cancelled,count(*) filter(where x.act_at between p_from and p_to and lower(coalesce(x.src,''))='incomplete' and lower(coalesce(x.st,'')) in ('cancelled','canceled')) incomplete_cancelled,count(*) filter(where x.act_at between p_from and p_to and lower(coalesce(x.src,'')) in ('web','incomplete') and lower(coalesce(x.st,'')) in ('pending','rts','shipped','delivered','pending_return','returned','partial','cancelled','canceled')) total from public.employees e left join epa x on x.actor=e.user_id where e.is_active=true group by e.user_id,e.name order by confirmed desc)
select jsonb_build_object('real',jsonb_build_object('created',(select count(*) from w),'total',(select count(*) from w),'processing',(select count(*) from p),'approved',(select count(*) from w where lower(coalesce(w.status::text,'')) in ('pending','rts','shipped','delivered','pending_return','returned','partial')),'pending',(select count(*) from p),'cancelled',(select count(*) from x),'revenue',(select coalesce(sum(total),0) from c),'allRevenue',(select coalesce(sum(total),0) from w)),'webOrders',jsonb_build_object('total',(select count(*) from w),'confirmed',(select count(*) from w where lower(coalesce(w.status::text,'')) in ('pending','rts','shipped','delivered','pending_return','returned','partial')),'processing',(select count(*) from p),'cancelled',(select count(*) from x)),'incompleteOrders',jsonb_build_object('total',(select count(*) from i),'confirmed',(select count(*) from i where lower(coalesce(i.status::text,'')) in ('pending','rts','shipped','delivered','pending_return','returned','partial')),'processing',(select count(*) from i where lower(coalesce(i.status::text,'')) in ('web_pending','processing')),'cancelled',(select count(*) from i where lower(coalesce(i.status::text,'')) in ('cancelled','canceled')),'active',(select count(*) from i where lower(coalesce(i.status::text,'')) not in ('cancelled','canceled'))),'profit',jsonb_build_object('grossSales',(select coalesce(sum(total),0) from c),'productCost',(select v from ic)),'sourceBreakdown',coalesce((select jsonb_agg(to_jsonb(s)) from s),'[]'::jsonb),'daily',coalesce((select jsonb_agg(to_jsonb(dy)) from dy),'[]'::jsonb),'hourly',coalesce((select jsonb_agg(jsonb_build_object('hour',hour_key,'orders',orders)) from hr),'[]'::jsonb),'employeePerformance',coalesce((select jsonb_agg(to_jsonb(ep)) from ep),'[]'::jsonb),'bestSelling',coalesce((select jsonb_agg(to_jsonb(b)) from b),'[]'::jsonb));
$function$

