// This file is automatically generated. Do not edit it directly.
import "@/lib/crypto-polyfill";
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { flushSupabaseEgressNow, recordSupabaseEgress, setSupabaseEgressSender } from '@/lib/supabase-egress-meter';

const PUBLIC_SUPABASE_URL = 'https://bvuhvzccziuniujeogng.supabase.co';
const PUBLIC_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_rapcUAgVGYdCuww7Q6GRNg__kFKVc17';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) headers.delete('Authorization');
    headers.set('apikey', supabaseKey);
    const method = (init?.method || (typeof Request !== 'undefined' && input instanceof Request ? input.method : 'GET')).toUpperCase();
    const response = await fetch(input, { ...init, headers });
    // Avoid cloning/reading every JSON response: Content-Length is cheap and avoids
    // duplicating potentially large response bodies on the hot path.
    const responseBytes = Number(response.headers.get('content-length') || 0);
    recordSupabaseEgress(input, method, response.status, Number.isFinite(responseBytes) ? responseBytes : 0);
    return response;
  };
}

function createSupabaseClient() {
  const runtimeEnv = typeof process !== 'undefined' ? process.env : undefined;
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || runtimeEnv?.['SUPABASE_URL'] || PUBLIC_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || runtimeEnv?.['SUPABASE_PUBLISHABLE_KEY'] || PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY) },
    auth: { storage: typeof window !== 'undefined' ? localStorage : undefined, persistSession: true, autoRefreshToken: true },
  });
  setSupabaseEgressSender(async (rows) => {
    await (client as any).rpc('record_endpoint_egress', { p_rows: rows });
  });
  if (typeof window !== 'undefined') {
    window.addEventListener('pagehide', flushSupabaseEgressNow, { passive: true });
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'hidden') flushSupabaseEgressNow();
    });
  }
  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
