// This file is automatically generated. Do not edit it directly.
import "@/lib/crypto-polyfill";
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { publicReadProxyUrl, isPublicAnonRead } from './public-read-proxy';

const PUBLIC_SUPABASE_URL = 'https://frtzlibogmethppqmhtr.supabase.co';
const PUBLIC_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_IwyqncvDdP4OF2UDNMlK9g_bn6Hu6n1';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string, supabaseUrl: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) headers.delete('Authorization');
    headers.set('apikey', supabaseKey);
    const method = (init?.method || (typeof Request !== 'undefined' && input instanceof Request ? input.method : 'GET')).toUpperCase();
    const rawUrl = typeof input === 'string' ? input : input instanceof URL ? input.toString() : (input as Request).url;
    const auth = headers.get('Authorization');
    const hasUserToken = Boolean(auth && auth !== `Bearer ${supabaseKey}`);
    const bodyText = typeof init?.body === 'string' ? init.body : undefined;
    const proxied = publicReadProxyUrl(rawUrl, supabaseUrl, method, bodyText, hasUserToken);
    if (proxied) {
      const proxyHeaders = new Headers();
      const accept = headers.get('Accept');
      if (accept) proxyHeaders.set('Accept', accept);
      const range = headers.get('Range');
      if (range) proxyHeaders.set('Range', range);
      {
        return await fetch(proxied, { method: 'GET', headers: proxyHeaders, signal: init?.signal ?? (input instanceof Request ? input.signal : undefined) });
      }
    }
    if (typeof window === 'undefined' && method === 'POST' && !hasUserToken && bodyText !== undefined && bodyText.length <= 500 && isPublicAnonRead(rawUrl, supabaseUrl, method, hasUserToken)) {
      const edge = (globalThis as { caches?: { default?: { match(r: Request): Promise<Response | undefined>; put(r: Request, res: Response): Promise<void> } } }).caches?.default;
      if (edge) {
        const keyReq = new Request(`${supabaseUrl}/__rpc-cache?u=${encodeURIComponent(rawUrl)}&b=${encodeURIComponent(bodyText)}`, { method: 'GET' });
        try { const hit = await edge.match(keyReq); if (hit) return hit; } catch {}
        const fresh = await fetch(input, { ...init, headers });
        if (fresh.ok) {
          const text = await fresh.text();
          const cacheable = new Response(text, { status: 200, headers: { 'Content-Type': fresh.headers.get('content-type') || 'application/json', 'Cache-Control': 'public, max-age=300' } });
          try { await edge.put(keyReq, cacheable.clone()); } catch {}
          return cacheable;
        }
        return fresh;
      }
    }
    if (typeof window === 'undefined' && isPublicAnonRead(rawUrl, supabaseUrl, method, hasUserToken)) {
      return fetch(input, { ...init, headers, cf: { cacheEverything: true, cacheTtl: 300 } } as RequestInit);
    }
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient(storageKey: string) {
  const runtimeEnv = typeof process !== 'undefined' ? process.env : undefined;
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || runtimeEnv?.['SUPABASE_URL'] || PUBLIC_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || runtimeEnv?.['SUPABASE_PUBLISHABLE_KEY'] || PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL) },
    auth: { storage: typeof window !== 'undefined' ? localStorage : undefined, storageKey, persistSession: true, autoRefreshToken: true },
  });
}

export const staffSupabase = createSupabaseClient('ss_staff_auth_frtzlibogmethppqmhtr_v1');
export const customerSupabase = createSupabaseClient('ss_customer_auth_frtzlibogmethppqmhtr_v1');

function getActiveClient() {
  if (typeof window === 'undefined') return staffSupabase;
  const path = window.location.pathname;
  const staffRoute = path === '/login' || path === '/admin' || path.startsWith('/admin/');
  return staffRoute ? staffSupabase : customerSupabase;
}

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    return Reflect.get(getActiveClient(), prop, receiver);
  },
});
